Null safety for Shimmer effect
flutter/website pull request #10071
Opened 2024-01-21 00:15 UTC by agavrel

_Description of what this PR is changing or adding, and why:_
check that `context.findRenderObject() != null`

_Issues fixed by this PR (if any):_
prevent "type 'Null' is not a subtype of type 'RenderBox' in type cast" segmentation fault

## Presubmit checklist

- [x] This PR doesn’t contain automatically generated corrections (Grammarly or similar).
- [x] This PR follows the [Google Developer Documentation Style Guidelines](https://developers.google.com/style) — for example, it doesn’t use _i.e._ or _e.g._, and it avoids _I_ and _we_ (first person).
- [x] This PR uses [semantic line breaks](https://github.com/dart-lang/site-shared/blob/main/doc/writing-for-dart-and-flutter-websites.md#semantic-line-breaks) of 80 characters or fewer.

2024-01-21 23:56 UTC, domesticmouse requested changes
Please see https://github.com/dart-lang/site-shared/blob/main/doc/code-excerpts.md on how to update the code excerpts. Thanks!

2024-01-25 09:36 UTC, navaronbracke commented on src/cookbook/effects/shimmer-loading.md
> +  bool get isSized => context.findRenderObject() != null
```suggestion
  bool get isSized => (context.findRenderObject() as RenderBox?)?.hasSize ?? false;
```

2024-01-29 01:22 UTC, domesticmouse commented
/gcbrun

2024-01-31 03:37 UTC, domesticmouse commented
/gcbrun

2024-01-31 03:38 UTC, domesticmouse approved these changes

2024-01-31 08:31 UTC, merged