Re-add Build Tools for Visual Studio 2022
flutter/website pull request #10118
Opened 2024-02-05 19:34 UTC by loic-sharma

_Description of what this PR is changing or adding, and why:_
Re-add the Build Tools for Visual Studio 2022 option. This is a significantly smaller download than a full Visual Studio installation.

This was originally added by https://github.com/flutter/website/pull/7484 but was removed by https://github.com/flutter/website/pull/9238.

_Issues fixed by this PR (if any):_

## Presubmit checklist

- [x] This PR doesn’t contain automatically generated corrections (Grammarly or similar).
- [x] This PR follows the [Google Developer Documentation Style Guidelines](https://developers.google.com/style) — for example, it doesn’t use _i.e._ or _e.g._, and it avoids _I_ and _we_ (first person).
- [x] This PR uses [semantic line breaks](https://github.com/dart-lang/site-shared/blob/main/doc/writing-for-dart-and-flutter-websites.md#semantic-line-breaks) of 80 characters or fewer.

2024-02-05 21:01 UTC, atsansone commented
Need to check out something with Legal first.

2024-02-05 21:02 UTC, atsansone requested changes
Setting to request changes to await Legal advice.

2024-02-06 15:44 UTC, loic-sharma commented on src/_includes/docs/install/reqs/windows/software.md
> +* [Visual Studio 2022][] with the the **Desktop development with C++**
TIL, updated!

2024-02-06 19:36 UTC, domesticmouse approved these changes

2024-02-12 20:24 UTC, sfshaza2 commented
What's the status here, @atsansone? I'd like to get this landed or closed, as the case may be.

2024-02-21 20:29 UTC, sfshaza2 commented
@atsansone, can you remove your "request changes" limitation?

2024-02-21 20:36 UTC, atsansone commented
@sfshaza2 : Not yet. I do have my guidance from Legal. I want to check with @anderdobo first. I'll do that today. Sorry for the delay.

2024-02-21 21:31 UTC, anderdobo commented
@atsansone I think this is a good option to include if there are no legal or other blockers.

2024-02-21 22:24 UTC, atsansone commented
/gcbrun

2024-02-21 22:42 UTC, atsansone approved these changes
LGTM. This may need some extra work later, but helps the user now.

2024-02-21 22:43 UTC, merged