Update internationalization.md to include the necessary import statement
flutter/website pull request #10248
Opened 2024-03-06 16:17 UTC by valerianaGit

Dev must import dependency for `import 'package:flutter_gen/gen_l10n/app_localizations.dart';` to be able to use app localizations.

_Description of what this PR is changing or adding, and why:_

_Issues fixed by this PR (if any):_

## Presubmit checklist

- [ ] This PR doesn’t contain automatically generated corrections (Grammarly or similar).
- [ ] This PR follows the [Google Developer Documentation Style Guidelines](https://developers.google.com/style) — for example, it doesn’t use _i.e._ or _e.g._, and it avoids _I_ and _we_ (first person).
- [ ] This PR uses [semantic line breaks](https://github.com/dart-lang/site-shared/blob/main/doc/writing-for-dart-and-flutter-websites.md#semantic-line-breaks) of 80 characters or fewer.

2024-03-06 20:20 UTC, domesticmouse commented
/gcbrun

2024-03-06 20:22 UTC, domesticmouse commented
Hey @valerianaGit we can't land this PR until the CLA is signed. Thanks!

2024-03-06 23:46 UTC, valerianaGit commented
@domesticmouse signed!

2024-03-07 04:05 UTC, domesticmouse commented
/gcbrun

2024-03-07 04:06 UTC, domesticmouse commented
I suspect this will fail the excepts test. The code you have changed is pulled from a backing `dart` file in the project referenced in the line above your change. You will need to make the change in both places.

2024-03-07 04:07 UTC, domesticmouse requested changes

2024-03-07 04:07 UTC, domesticmouse commented on src/ui/accessibility-and-internationalization/internationalization.md
>     <?code-excerpt "gen_l10n_example/lib/main.dart (InternationalizedTitle)"?>
You'll need to modify this code as well

2024-03-12 18:21 UTC, sfshaza2 commented
/gcbrun

2024-04-03 18:35 UTC, sfshaza2 commented
/gcbrun

2024-05-07 16:27 UTC, parlough commented
Thanks so much for the PR!

Since the PR been sitting for a while with changes requested, I'm going to close it for now. However, if you want to revisit the PR, please feel free to reopen it or open a new one.

I will note, that this step is a continuation of the previous step which does highlight adding this import. This snippet is intended to just be a focused portion of the file. Is there some way we can make that more clear, either textually or visually?

Thanks again :)

2024-05-07 16:27 UTC, closed without merging