FWE: Handling user input (v1)
flutter/website pull request #10284
Opened 2024-03-14 04:56 UTC by khanhnwin

_Description of what this PR is changing or adding, and why:_ The initial "Handling user input" page for FWE v1

2024-03-14 17:27 UTC, sfshaza2 reviewed
Thanks for doing this on such short notice, @khanhnwin (well, kinda sorta), and when you're swamped with I/O. I made quite a few edits, but just accepting at least some of them should make your life easier...

2024-03-14 17:27 UTC, sfshaza2 commented on src/get-started/fwe/user-input.md
> +[DropdownMenu (Widget of the Week)]: https://youtu.be/giV9AbM2gd8?si=E23hjg72cjMTe_mz
```suggestion
[`TextField`]: {{site.api}}flutter/material/TextField-class.html
[Create and style a text field]: /cookbook/forms/text-input
[Retrieve the value of a text field]: /cookbook/forms/retrieve-input
[Handle changes to a text field]: /cookbook/forms/text-field-changes
[Focus and text fields]: /cookbook/forms/focus
[`RichText`]: {{site.api}}flutter/widgets/RichText-class.html
[Rich Text (Widget of the Week)]: https://www.youtube.com/watch?v=rykDVh-QFfw
[Rich Text Editor]: https://flutter.github.io/samples/rich_text_editor.html
[Rich Text Editor code]: https://github.com/flutter/samples/tree/main/simplistic_editor
[`Form`]: {{site.api}}flutter/widgets/Form-class.html
[Build a form with validation]: /cookbook/forms/validation
[Form App]: https://flutter.github.io/samples/web/form_app/
[Form App Code]: https://github.com/flutter/samples/tree/main/form_app
[`SelectableText`]: {{site.api}}flutter/material/SelectableText-class.html
[SelectableText (Widget of the Week)]: https://www.youtube.com/watch?v=ZSU3ZXOs6hc

[`SegmentedButton`]: {{site.api}}flutter/material/SegmentedButton-class.html
[`DropdownMenu`]: {{site.api}}flutter/material/DropdownMenu-class.html
[DropdownMenu (Widget of the Week)]: https://youtu.be/giV9AbM2gd8?si=E23hjg72cjMTe_mz
```

2024-03-14 17:27 UTC, sfshaza2 commented on src/get-started/fwe/user-input.md
> +[Semantics (Flutter Widget of the Week)]: https://youtu.be/NvtMt_DtFrQ?si=o79BqAg9NAl8EE8_
```suggestion
[`Dismissible`]: {{site.api}}flutter/widgets/Dismissible-class.html
[Dismissible (Widget of the Week)]: https://youtu.be/iEMgjrfuc58?si=f0S7IdaA9PIWIYvl
[Implement swipe to dismiss]: /cookbook/gestures/dismissible
[pkg:`flutter_slidable`]: https://pub.dev/packages/flutter_slidable
[flutter_slidable (Package of the Week)]: https://www.youtube.com/watch?v=QFcFEpFmNJ8

[GestureDetector (Widget of the Week)]: https://www.youtube.com/watch?v=WhVXkCFPmK4
[Taps, drags, and other gestures]: /ui/interactivity/gestures#gestures
[Handle taps]: /cookbook/gestures/handling-taps
[Semantics (Flutter Widget of the Week)]: https://youtu.be/NvtMt_DtFrQ?si=o79BqAg9NAl8EE8_
```

2024-03-14 17:28 UTC, sfshaza2 requested changes
Changing status to request changes, since Brett already approved.

2024-03-14 17:29 UTC, sfshaza2 commented
Also, Khanh, that first section you use bulleted lists for the widgets. But in subsequent sections, you don't. I haven't looked at the generated page yet, but please be consistent. thx!

2024-03-14 17:57 UTC, khanhnwin commented on src/get-started/fwe/user-input.md
> +For an introduction to how you can change app state in response to user interactions, check out the following tutorial which teaches you how to build a "favorite" button:
I love whitespace! I will agree to this revision anyway XD

2024-03-14 17:58 UTC, khanhnwin commented on src/get-started/fwe/user-input.md
> +Now that you've gotten a feel for how user interaction works, check out the [Material 3 Demo][] which samples some of the various user input widgets available in the Material 3 component library.
TIL!

2024-03-14 17:59 UTC, khanhnwin commented on src/get-started/fwe/user-input.md
> +Note: This page focuses on Material 3 widgets because it is the library that many developers start with when learning Flutter. However, Flutter also supports other component libraries such as [Cupert
There are other packages available too. Ex: [macos_ui](https://pub.dev/packages/macos_ui)

2024-03-14 19:53 UTC, khanhnwin commented on src/get-started/fwe/user-input.md
> +* Video: [FloatingActionButton (Widget of the Week)][]
They're all technically buttons, but not the same type of "core" buttons.

2024-03-14 20:04 UTC, khanhnwin commented on src/get-started/fwe/user-input.md
> +* Video: [FloatingActionButton (Widget of the Week)][]
I added them to the list!

2024-03-14 20:04 UTC, domesticmouse commented
Both the GitHub markdown preview and the link checker don't like this change:

```console
Checking for broken Markdown link references...
Error: Invalid link references found!

get-started/fwe/user-input/index.html:
[TextField][]
```

2024-03-14 22:41 UTC, khanhnwin commented
ptal @sfshaza2!

2024-03-14 22:41 UTC, khanhnwin commented
/gcbrun

2024-03-15 18:55 UTC, sfshaza2 approved these changes
Thanks, @khanhnwin! There are still some formatting issues, but I'm going to land this and fix them in my index PR.

2024-03-15 18:56 UTC, merged

2024-03-15 20:01 UTC, khanhnwin commented
Thanks @sfshaza2!