Add Explain how to open a drawer
flutter/website pull request #10548
Opened 2024-05-09 06:38 UTC by sudot

Resolve #10519

2024-05-09 06:43 UTC, domesticmouse commented
> Resolve #10519

I don't see how this PR is related to that issue.

2024-05-09 21:13 UTC, sfshaza2 requested changes
Hi, @farcaller!

- This is a great improvement, thx! However, the build tests are failing. When you change the code, you have to re-run the refresh code excerpts script. (This is described in the site README.)
- Also, I found one typo. Can you fix that?
- @craiglabenz, can you otherwise review the code in this PR?

2024-05-09 21:13 UTC, sfshaza2 commented on src/content/cookbook/design/drawer.md
> +Because when leading is `null`, the default implementation in `AppBar` is `DrawerButton`.
When leading <WHAT> is null?

2024-05-09 22:03 UTC, craiglabenz requested changes
Thanks, @sudot. This LGTM once the build is passing. One of the problems is formatting (should be an easy fix), and the other error message can be found here: https://github.com/flutter/website/actions/runs/9013474562/job/24764429256?pr=10548

2024-05-10 09:02 UTC, domesticmouse commented
/gcbrun

2024-05-10 19:04 UTC, craiglabenz approved these changes
LGTM

2024-05-10 21:12 UTC, craiglabenz commented
It looks like the staging build failed because my (personal Gmail) account lacks permissions in Cloud Build for this project.

IMO we can either safely merge or someone whose GitHub account is tied to a Google Cloud account with sufficient permissions can re-merge in `main` to trigger the job again.

2024-05-12 20:45 UTC, sfshaza2 commented
/gcbrun

2024-05-12 20:51 UTC, sfshaza2 approved these changes
Thanks, @sudot and @craiglabenz!

2024-05-12 20:51 UTC, merged