Updating the iOS/macOS flavors doc
flutter/website pull request #10716
Opened 2024-06-06 18:56 UTC by sfshaza2

Fixes https://github.com/flutter/website/issues/10713,
for setting up flavors in iOS and macOS.

cc @qwadrox

2024-06-06 20:19 UTC, jmagman requested changes
https://github.com/flutter/website/issues/10713 is reporting an issue in adding a flavor (prod) that isn't described in these docs.  These instructions are only for adding the "free" flavor, they don't say anything about prod.  

And we already have the correct instructions for updating the Podfile here:
https://docs.flutter.dev/deployment/flavors#plugin-configurations

2024-06-06 20:19 UTC, jmagman commented on src/content/deployment/flavors.md
> +### Manually update podfile
Casing nit: Podfile
```suggestion
### Manually update Podfile
```

2024-06-06 20:19 UTC, jmagman commented on src/content/deployment/flavors.md
> +you will need to manually update your podfile.
```suggestion
you will need to manually update your Podfile.
```

2024-06-06 20:19 UTC, jmagman commented on src/content/deployment/flavors.md
> +3. Run `pod install`.
Flutter developers should never need to run `pod install` (except for add-to-app).  If we have instructions to explicitly run it anywhere else in the docs, we should remove it.
You can delete steps 2 and 3 and go right to "Build the app."

2024-06-06 20:22 UTC, jmagman commented
Reading it again, the fix for https://github.com/flutter/website/issues/10713 would be to just add the instructions for updating the xcconfig, as they say in their workaround section:
```diff
- #include? "Pods/Target Support Files/Pods-Runner/Pods-Runner.debug.xcconfig"
+ #include? "Pods/Target Support Files/Pods-Runner/Pods-Runner.debug-free.xcconfig"
```
Example from our integration docs:
https://github.com/flutter/flutter/blob/32da263b1d5590a98e03d0ea1374f85e0c18de3f/dev/integration_tests/flavors/ios/Flutter/Debug.xcconfig#L3

2024-06-06 20:52 UTC, qwadrox commented
> Reading it again, the fix for #10713 would be to just add the instructions for updating the xcconfig, as they say in their workaround section:
> 
> ```diff
> - #include? "Pods/Target Support Files/Pods-Runner/Pods-Runner.debug.xcconfig"
> + #include? "Pods/Target Support Files/Pods-Runner/Pods-Runner.debug-free.xcconfig"
> ```
> 
> Example from our integration docs: https://github.com/flutter/flutter/blob/32da263b1d5590a98e03d0ea1374f85e0c18de3f/dev/integration_tests/flavors/ios/Flutter/Debug.xcconfig#L3

What is the purpose of xcconfig files?
If I have 3 scheme like prod, uat, dev, should I duplicate the 'Debug' => :debug block in podfile 3 times? like  'Debug-prod' => :debug, ... etc. 
First I thought I have to have 3 line per scheme as well in the xcconfig files: #include? like 
```
"Pods/Target Support Files/Pods-Runner/Pods-Runner.debug-prod.xcconfig"
"Pods/Target Support Files/Pods-Runner/Pods-Runner.debug-dev.xcconfig"
"Pods/Target Support Files/Pods-Runner/Pods-Runner.debug-uat.xcconfig"
```
But it seems one is enough

2024-06-07 17:41 UTC, jmagman commented
> What is the purpose of xcconfig files?

It's an Xcode concept to add build configurations to your project:
https://developer.apple.com/documentation/xcode/adding-a-build-configuration-file-to-your-project

You likely only needed one because they are all identical.

2024-06-07 18:10 UTC, qwadrox commented
> > What is the purpose of xcconfig files?
> 
> It's an Xcode concept to add build configurations to your project:
> https://developer.apple.com/documentation/xcode/adding-a-build-configuration-file-to-your-project
> 
> You likely only needed one because they are all identical.

I understand now. Thanks. 
The error occurred because I renamed both schemes. I renamed the original Runner scheme to 'prod', which caused the imported Pod generated config to be incorrectly referenced in Debug.xconfig.

The original documentation is correct; it only advises creating a new scheme, leaving the Runner scheme unchanged. This maintains the correct reference paths in Debug.xconfig.

It would be only beneficial to add a cautionary note to the docs: 

"If you rename the original Runner scheme, ensure you update Debug.xcconfig and Release.xcconfig in the ios/Flutter directory to reference the newly generated Pods/Target Support Files/Pods-Runner xcconfig file."

2024-06-10 18:41 UTC, atsansone commented
@sfshaza2 : I have a larger refactor of this whole page in flight. I'll integrate your changes to it and then we can close this PR. Does that work for you?

2024-06-11 17:37 UTC, sfshaza2 commented
@atsansone, I'd have preferred if you had talked about this with me ahead of time.

2024-06-11 17:37 UTC, closed without merging