Grammatically updated the docs.
flutter/website pull request #4638
Opened 2020-09-21 17:01 UTC by KevalPrajapati

A small change to a line on [docs](https://flutter.dev/docs#docs) which would make the sentence complete.

2020-09-21 17:04 UTC, KevalPrajapati commented
@googlebot I signed it!

2020-09-21 21:45 UTC, sfshaza2 requested changes
This is an ok edit, though "Flutter" needs to be capitalized. :)

2020-09-22 03:34 UTC, KevalPrajapati commented
> This is an ok edit, though "Flutter" needs to be capitalized. :)

Okay. I would do that.

2020-09-22 03:43 UTC, KevalPrajapati commented
> This is an ok edit, though "Flutter" needs to be capitalized. :)

Done the changes.

2020-09-23 04:38 UTC, KevalPrajapati commented
> This is an ok edit, though "Flutter" needs to be capitalized. :)

Done the changes in the second commit. Please review.

2020-09-23 04:50 UTC, KevalPrajapati commented on src/docs/index.md
> +Coming from another platform? Check out Flutter for:
Capitalized F in Flutter.

2020-09-23 05:20 UTC, closed without merging