Added a migration guide for TextSelectionTheme.
flutter/website pull request #4655
Opened 2020-09-24 19:11 UTC by darrenaustin

Added a migration guide for the `TextSelectionTheme` breaking change described in: https://flutter.dev/go/text-selection-theme.

2020-09-24 19:19 UTC, sfshaza2 requested changes
The guide itself is missing, @darrenaustin. Did you forget a "git add <file>"?

2020-09-24 19:22 UTC, darrenaustin commented
> The guide itself is missing, @darrenaustin. Did you forget a "git add "?

D'oh! Indeed I did. Sorry about that.

2020-09-24 21:19 UTC, sfshaza2 commented
@darrenaustin, can you fix the conflict? These breaking change docs can come in so fast...

2020-09-24 23:00 UTC, darrenaustin commented
> @darrenaustin, can you fix the conflict? These breaking change docs can come in so fast...

Yup, looking now. I haven't set up my tree to do a full website build, so this is a good exercise. Sorry I didn't do this before checking in.

2020-10-02 00:38 UTC, sfshaza2 approved these changes
LGTM

2020-10-02 00:38 UTC, merged