Update vs-code.md
flutter/website pull request #4860
Opened 2020-10-12 02:02 UTC by micpap25

NOTE: We love contributions, but we hate spam. If your PR doesn't improve flutter.dev, we'll close it and label it as `invalid`.

Fixes #4150

Changes proposed in this pull request:

*  Add a section about targeting build modes for VS Code

2020-10-12 18:40 UTC, sfshaza2 requested changes
Overall this is really good. Just a couple small things, since you create quite a few PRs.  :)

Also, I staged your PR here:  https://sz-flutter.firebaseapp.com/docs/development/tools/vs-code#run-app-in-debug-profile-or-release-mode

2020-10-12 18:40 UTC, sfshaza2 commented on src/docs/development/tools/vs-code.md
> +     the Run view in VS Code and click **create a launch.json file**.
=> Bold the "Run" text. (Bold menu items:  https://developers.google.com/style/ui-elements)

2020-10-12 18:40 UTC, sfshaza2 commented on src/docs/development/tools/vs-code.md
> +     your `launch.json` may look like this:
may => might. (Avoid "may": https://developers.google.com/style/word-list#may)

Also, we don't use bulleted lists for formatting. To have the "For example, ..." to break on a new line, just put a <br> at the end of the previous line. (Also, a one-item list is discouraged...)

2020-10-12 18:40 UTC, sfshaza2 commented on src/docs/development/tools/vs-code.md
> + 1. Run the app through the Run view.
=> Run the app through the **Run** view.

2020-10-18 04:01 UTC, micpap25 commented
Should be fixed now! I'll keep those style guides on-hand from now on, haha.

2020-10-19 17:41 UTC, sfshaza2 approved these changes
LGTM

2020-10-19 17:42 UTC, merged