Update adoptawidget page with list of contributions
flutter/website pull request #4980
Opened 2020-11-11 17:58 UTC by johnpryan

Staged: https://flutter-website-jr-stagi-988d4.firebaseapp.com/adoptawidget

2020-11-11 19:00 UTC, sfshaza2 commented on src/adoptawidget/index.md
> +
@johnpryan, this looks pretty good, but I feel like it's missing some text. How about adding something like:

Thanks to your eager participation, all of the widgets were assigned in xxx hours and all issues have been addressed, though we are still reviewing PRs. Based on the success of this experiment, we may do something similar in the future, so stay tuned!

2020-11-11 19:01 UTC, sfshaza2 requested changes
thx!

2020-11-12 21:59 UTC, johnpryan commented
@sfshaza2 this is ready for another look

2020-11-12 23:04 UTC, sfshaza2 approved these changes
LGTM

2020-11-12 23:04 UTC, merged