General overhaul of FAQ
flutter/website pull request #4994
Opened 2020-11-18 00:19 UTC by timsneath

Changes proposed in this pull request:

* Overhauled and updated many sections of the FAQ

2020-11-30 18:05 UTC, sfshaza2 requested changes
A few things. Overall, a big improvement.

2020-11-30 18:05 UTC, sfshaza2 commented on src/docs/resources/faq.md
> +to join the community and contribute to Flutter!
=>
```
[contribute to Flutter][]!

[contribute to Flutter]: {{site.github}}/flutter/flutter/blob/master/CONTRIBUTING.md
```

2020-12-01 04:45 UTC, timsneath commented on src/docs/resources/faq.md
> +the world, and is free and open source.
:) I just word wrapped it here... can you hear Martin saying these words though?

2020-12-01 04:45 UTC, timsneath commented on src/docs/resources/faq.md
> +its ability to turn concepts to be turned into production code without the
Good catch!

2020-12-01 04:46 UTC, timsneath commented on src/docs/resources/faq.md
> +Flutter is designed to support for 2D mobile apps that run on both Android and
What _was_ I thinking? Thanks :)

2020-12-01 04:49 UTC, timsneath commented on src/docs/resources/faq.md
> +Yes! Flutter ships with a modern reactive framework. Flutter's framework is
Fixed

2020-12-01 04:52 UTC, timsneath commented on src/docs/resources/faq.md
> +Of course, we recommend that you measure your own app. To do that, see
I'm sorry! I use a fantastic VSCode extension called Rewrap, which just takes care of wrapping. It's configured (by default) to wrap on 80 columns.

2020-12-01 04:56 UTC, timsneath commented
OK, updated. Thanks for the great review, @sfshaza2!

2020-12-01 17:18 UTC, sfshaza2 approved these changes
Thanks for improving this! LGTM

2020-12-01 17:18 UTC, merged