Breaking Change entry for dry layout on RenderBox
flutter/website pull request #5007
Opened 2020-11-21 01:24 UTC by goderbauer

Breaking Change entry for https://github.com/flutter/flutter/pull/70656

2020-11-21 01:54 UTC, gspencergoog requested changes
Maybe make all of the class/member references into links?

2020-11-21 01:54 UTC, gspencergoog commented on src/docs/release/breaking-changes/renderbox-dry-layout.md
> +calculations. Subclasses, that implement `computeDryLayout` no longer need to
```suggestion
calculations. Subclasses that implement `computeDryLayout` no longer need to
```

2020-11-21 01:54 UTC, gspencergoog commented on src/docs/release/breaking-changes/renderbox-dry-layout.md
> +`RenderBox` protocol. The method receives a set of `BoxConstraints` and is
```suggestion
A new method, `computeDryLayout`, was added to the `RenderBox` protocol to correctly
calculate the intrinsic sizes of a `RenderParagraph` with `WidgetSpan` children and a `RenderWrap`. The method receives a set of `BoxConstraints` and is
```

2020-11-21 01:54 UTC, gspencergoog commented on src/docs/release/breaking-changes/renderbox-dry-layout.md
> +`RenderBox.computeMinIntrinsicWidth` and friends).
Maybe make this a link?
```suggestion
[`RenderBox.computeMinIntrinsicWidth`] and friends).
```

2020-11-21 01:54 UTC, gspencergoog commented on src/docs/release/breaking-changes/renderbox-dry-layout.md
> +if they are used as a descendant of a RenderObject that may query the intrinsic
```suggestion
if they are used as a descendant of a `RenderObject` that may query the intrinsic
```

2020-11-21 01:54 UTC, gspencergoog commented on src/docs/release/breaking-changes/renderbox-dry-layout.md
> +to the `size` setter, it needs to return the computed size. If `computeDryLayout`
```suggestion
to the `size` setter, it returns the computed size. If `computeDryLayout`
```

2020-11-21 01:54 UTC, gspencergoog commented on src/docs/release/breaking-changes/renderbox-dry-layout.md
> + @override
```suggestion
  @override
```

2020-12-07 19:12 UTC, goderbauer commented on src/docs/release/breaking-changes/renderbox-dry-layout.md
> +`RenderBox.computeMinIntrinsicWidth` and friends).
Done.

2020-12-07 19:12 UTC, goderbauer commented
@sfshaza2 Thanks for applying the suggestions.

@gspencergoog Fixed the other comment, PTAL.

2020-12-08 19:18 UTC, gspencergoog approved these changes
![32384589-a60f0e74-c078-11e7-9bc1-e5b5287aea9d](https://user-images.githubusercontent.com/8867023/37737237-66e9c9dc-2d10-11e8-8797-13a405eace49.png)

2020-12-11 21:05 UTC, merged

2021-01-13 02:45 UTC, AlexV525 commented on src/docs/release/breaking-changes/renderbox-dry-layout.md
> +[Issue 48679]: {{site.github}}/flutter/flutter/issues/48679]
Extra `]`?