Add flokk to samples and codelabs
flutter/website pull request #5341
Opened 2021-02-23 02:39 UTC by domesticmouse

Adding gskinner's flokk desktop app to the codelabs and sample apps section.

2021-02-23 04:05 UTC, domesticmouse commented on src/desktop.md
> +: A fresh and modern Google Contacts manager that integrates with GitHub and Twitter
@csells can you word smith this into something less sales-y?

2021-02-23 04:05 UTC, sfshaza2 requested changes
Can we make this more factual and less marketing-ish?

2021-02-24 02:26 UTC, sfshaza2 commented
@csells, can you review this asap? Otherwise I can't accept it before freezing the website repo tomorrow morning for some planned updates. thx

2021-02-24 08:06 UTC, sfshaza2 approved these changes
@domesticmouse, I think Chris has too much going on, but I am ok with my suggested text.  :)

2021-02-24 08:06 UTC, sfshaza2 commented on src/desktop.md
> +  Github accounts for each contact, and see all of their social activities at a glance.
```suggestion
Flokk [announcement blogpost][gskinner-flokk-blogpost], [repo][gskinner-flokk-repo]
: A Google contacts manager that integrates with GitHub and Twitter. 
  It syncs with your Google account, imports your contacts,
  and allows you to manage them.
```

2021-02-24 08:06 UTC, sfshaza2 commented on src/desktop.md
> +[gskinner-flokk-blogpost]: https://blog.gskinner.com/archives/2020/09/flokk-how-we-built-a-desktop-app-using-flutter.html
```suggestion
[flutter-gallery-repo]: {{site.github}}/flutter/flutter/tree/master/dev/integration_tests/flutter_gallery
[gskinner-flokk-repo]: {{site.github}}/gskinnerTeam/flokk
[gskinner-flokk-blogpost]: https://blog.gskinner.com/archives/2020/09/flokk-how-we-built-a-desktop-app-using-flutter.html
```

2021-02-24 08:10 UTC, merged