Add member to cached FlutterEngine Java example
flutter/website pull request #5630
Opened 2021-04-14 20:52 UTC by ryansama

The Kotlin example has the `lateinit var flutterEngine` member variable shown but the Java version does not.

2021-04-14 20:54 UTC, ryansama commented
@googlebot I signed it!

2021-04-15 05:58 UTC, sfshaza2 reviewed
@miquelbeltran, is this PR correct with the code excerpt?

2021-04-15 07:58 UTC, miquelbeltran commented
The original code-excerpt code seems to be wrong, because they are commented out, for example:
```
<!--code-excerpt "MyApplication.java" title-->
```
instead of
```
<? code-excerpt "MyApplication.java" title ?>
```
so the refresh-code-excerpts script does nothing.

You can merge this change, but the original code excerpt tags need to be fixed as well.

2021-04-15 16:32 UTC, sfshaza2 commented
Oh, I hadn't noticed that! @ryansama, we certainly can't comment out the code excerpt portion. Can you fix this? Or should I close this PR?

2021-04-15 16:33 UTC, sfshaza2 requested changes
Reinstate code excerpts.

2021-04-17 00:31 UTC, ryansama commented
> Oh, I hadn't noticed that! @ryansama, we certainly can't comment out the code excerpt portion. Can you fix this? Or should I close this PR?

Hi @sfshaza2 I uncommented the line above my change -- should I also uncomment every other code-excerpt in the file?

2021-04-20 17:26 UTC, sfshaza2 requested changes
@ryansama, I'm not sure why any code excerpts would be commented out. I searched and found just one other instance where it was commented out. I'd say, yes, remove that.

2021-04-26 22:31 UTC, sfshaza2 approved these changes
Thanks, @ryansama! LGTM

2021-04-27 20:10 UTC, sfshaza2 commented
@miquelbeltran, uncommenting the code excerpts (which the original poster didn't comment out), is causing breakage. Can you take a quick looksie?

2021-04-28 03:16 UTC, sfshaza2 commented
OK, this build is breaking on a reverted change (required version of english_words package). This PR doesn't even modify that text. Merging manually.

2021-04-28 03:16 UTC, merged