update code sample cookbook background parsing
flutter/website pull request #5798
Opened 2021-05-16 13:32 UTC by iapicca

fix https://github.com/flutter/flutter/issues/82635

updating the current coda sample with the following

<details>
<summary>new code sample</summary>

```dart
import 'dart:async';
import 'dart:convert';

import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;

Future<List<Photo>> fetchPhotos(http.Client client) async {
  final uri = Uri.parse('https://jsonplaceholder.typicode.com/photos');
  final response = await client.get(uri);

  // Use the compute function to run parsePhotos in a separate isolate.
  return compute(parsePhotos, response.body);
}

// A function that converts a response body into a List<Photo>.
List<Photo> parsePhotos(String responseBody) {
  final parsed = jsonDecode(responseBody) as List;
  return [for (final json in parsed) Photo.fromJson(json)];
}

@immutable
class Photo {
  final int albumId;
  final int id;
  final String title;
  final String url;
  final String thumbnailUrl;

  const Photo({
    required this.albumId,
    required this.id,
    required this.title,
    required this.url,
    required this.thumbnailUrl,
  });

  factory Photo.fromJson(Map<String, Object?> json) {
    return Photo(
      albumId: json['albumId'] as int,
      id: json['id'] as int,
      title: json['title'] as String,
      url: json['url'] as String,
      thumbnailUrl: json['thumbnailUrl'] as String,
    );
  }
}

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    final appTitle = 'Isolate Demo';

    return MaterialApp(
      title: appTitle,
      home: MyHomePage(title: appTitle),
    );
  }
}

class MyHomePage extends StatelessWidget {
  final String title;

  const MyHomePage({Key? key, required this.title}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(title),
      ),
      body: FutureBuilder<List<Photo>>(
        future: fetchPhotos(http.Client()),
        builder: (context, snapshot) {
          if (snapshot.hasError) {
            print(snapshot.error);
            return const Center(child: Icon(Icons.error));
          }
          return snapshot.hasData
              ? PhotosList(photos: snapshot.data!)
              : const Center(child: CircularProgressIndicator());
        },
      ),
    );
  }
}

class PhotosList extends StatelessWidget {
  final List<Photo> photos;

  const PhotosList({Key? key, required this.photos}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return GridView.builder(
      gridDelegate: const SliverGridDelegateWithFixedCrossAxisCount(
        crossAxisCount: 2,
      ),
      itemCount: photos.length,
      itemBuilder: (context, index) {
        return Image.network(photos[index].thumbnailUrl);
      },
    );
  }
}

```

</details>

testing the code above with the latest master on android physical device

<details>
<summary>doctor</summary>

```console
[✓] Flutter (Channel master, 2.3.0-2.0.pre.234, on Ubuntu 21.04 5.11.0-17-generic, locale en_US.UTF-8)
    • Flutter version 2.3.0-2.0.pre.234 at /home/yakforward/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 89442b495e (33 hours ago), 2021-05-14 21:34:02 -0700
    • Engine revision 3c1d96f0b8
    • Dart version 2.14.0 (build 2.14.0-edge.a527411e5100a0a4f48c4009087a1b988aa784af)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/yakforward/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /snap/android-studio/101/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 12.0.0-1ubuntu1
    • cmake version 3.18.4
    • ninja version 1.10.1
    • pkg-config version 0.29.2

[✓] Android Studio (version 4.1)
    • Android Studio at /snap/android-studio/101/android-studio
    • Flutter plugin version 55.1.1
    • Dart plugin version 201.9335
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (3 available)
    • Pixel 3a (mobile) • 965AY0WP5C • android-arm64  • Android 11 (API 30)
    • Linux (desktop)   • linux      • linux-x64      • Ubuntu 21.04 5.11.0-17-generic
    • Chrome (web)      • chrome     • web-javascript • Google Chrome 90.0.4430.212

• No issues found!

```

</details>

everything seems to work as intended

<details>
<summary>logs</summary>

```
[  +66 ms] executing: uname -m
[  +32 ms] Exit code 0 from: uname -m
[        ] x86_64
[   +6 ms] executing: [/home/yakforward/development/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +8 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 89442b495e5a3537d53247f49d7ac32bf3784af8
[   +1 ms] executing: [/home/yakforward/development/flutter/] git tag --points-at 89442b495e5a3537d53247f49d7ac32bf3784af8
[  +12 ms] Exit code 0 from: git tag --points-at 89442b495e5a3537d53247f49d7ac32bf3784af8
[   +1 ms] executing: [/home/yakforward/development/flutter/] git describe --match *.*.* --long --tags 89442b495e5a3537d53247f49d7ac32bf3784af8
[  +35 ms] Exit code 0 from: git describe --match *.*.* --long --tags 89442b495e5a3537d53247f49d7ac32bf3784af8
[        ] 2.3.0-1.0.pre-234-g89442b495e
[   +8 ms] executing: [/home/yakforward/development/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +5 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [/home/yakforward/development/flutter/] git ls-remote --get-url origin
[   +4 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +80 ms] executing: [/home/yakforward/development/flutter/] git rev-parse --abbrev-ref HEAD
[   +4 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[  +83 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +90 ms] executing: /home/yakforward/Android/Sdk/platform-tools/adb devices -l
[  +43 ms] List of devices attached
           965AY0WP5C             device usb:1-2 product:sargo model:Pixel_3a device:sargo transport_id:4
[   +6 ms] /home/yakforward/Android/Sdk/platform-tools/adb -s 965AY0WP5C shell getprop
[ +113 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +8 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping upda [...]

2021-05-17 05:45 UTC, sfshaza2 reviewed
@miquelbeltran, please review

2021-05-17 05:51 UTC, miquelbeltran commented
Hi @iapicca All the code changes need to be done on the original dart files as well and exported using the refresh code excerpts tool, rather than editing the mark down directly. Please look at the README.md and the https://github.com/dart-lang/site-shared/blob/master/doc/code-excerpts.md for more info on how to do it.

2021-05-17 06:31 UTC, sfshaza2 commented
That's what I was kind of assuming, but I didn't take the time to look at the site. @iapicca, are you willing to tackle that? If not, I will close the PR.

2021-05-17 06:36 UTC, iapicca commented
> That's what I was kind of assuming, but I didn't take the time to look at the site. @iapicca, are you willing to tackle that? If not, I will close the PR.

@sfshaza2 
I'm definitely willing to try;
I asked guidance on discord, because the [instructions](https://github.com/dart-lang/site-shared/blob/master/doc/code-excerpts.md) are not clear to me

2021-05-17 07:46 UTC, miquelbeltran requested changes
I think I spotted a couple of issues.

2021-05-17 07:46 UTC, miquelbeltran commented on null_safety_examples/cookbook/networking/background_parsing/lib/main_step2.dart
> +  final response = await client.get(uri);
Missing return?

2021-05-17 07:46 UTC, miquelbeltran commented on null_safety_examples/cookbook/networking/background_parsing/lib/main_step3.dart
> +  return compute(parsePhotos, response.body);
In the step 3, we don't use the `compute` function yet, the change is made in the step 4.

The comment in the line 17 should be removed instead.

2021-05-20 19:43 UTC, sfshaza2 commented
Is this ready? Do you approve, @miquelbeltran?

2021-05-23 07:24 UTC, miquelbeltran commented
@sfshaza2 the code excerpts are not correct yet, I run the `./tool/refresh-code-excerpts.sh` localy and got changes still. Also the GitHub workflow needs run approval, but I cannot do that.

2021-05-23 09:46 UTC, iapicca commented
> [..] the code excerpts are not correct yet

@miquelbeltran 
I applied the changes requested [here](https://github.com/flutter/website/pull/5798#discussion_r633295197) and [here](https://github.com/flutter/website/pull/5798#discussion_r633292330) in [this commit](4bb6628)
I'd be happy to fix the excerpts on a feedback

2021-05-24 00:59 UTC, sfshaza2 commented
I've kicked off the workflow. @domesticmouse, do you have the privilege to kick off the workflow?

2021-05-24 01:45 UTC, domesticmouse commented
My laptop is borked. I'm currently at seriously reduced capability.

2021-05-24 13:37 UTC, iapicca commented
I see both tests
- Stable channel: code check, stable, tool/check-code.sh, false) (pull_request) 
- Stable channel: null safety code check, stable, tool/check-code.sh --null-safety, false)

fails with the same output

 <details>
<summary>error</summary>

>   Source:     /home/runner/work/website/website/src
>   Fragments:  /home/runner/work/website/website/tmp/_fragments/examples
>   Other args: --yaml --no-escape-ng-interpolation --replace=/\/\/!<br>//g;/ellipsis(<\w+>)?(\(\))?;?/.../g;/\/\*(\s*\.\.\.\s*)\*\//$1/g;/\{\/\*-(\s*\.\.\.\s*)-\*\/\}/$1/g;/\/\/!(analysis-issue|runtime-error)[^\n]*//g;/\x20*\/\/\s+ignore_for_file:[^\n]+\n//g;/\x20*\/\/\s+ignore:[^\n]+//g;
>   
>   Error: /home/runner/work/website/website/src/docs/cookbook/networking/background-parsing.md:146 cannot read file "/home/runner/work/website/website/tmp/_fragments/examples/../null_safety_examples/cookbook/networking/background_parsing/lib/main.dart.excerpt.yaml"
>   Processed 388 Dart/Jade/Markdown files: 3 out of 338 fragments needed updating.
>   
>   Error: some code excerpts need to be refreshed. You'll need to
>   rerun '/home/runner/work/website/website/tool/refresh-code-excerpts.sh' locally, and re-commit.
>   diff --git a/src/docs/cookbook/networking/background-parsing.md b/src/docs/cookbook/networking/background-parsing.md
>   index dd79c72..55c61db 100644
>   --- a/src/docs/cookbook/networking/background-parsing.md
>   +++ b/src/docs/cookbook/networking/background-parsing.md
>   @@ -54,7 +54,7 @@ using the [`http.get()`][] method.
>    ```diff
>    Future<http.Response> fetchPhotos(http.Client client) async {
>      final uri = Uri.parse('https://jsonplaceholder.typicode.com/photos');
>   -  final response = await client.get(uri);
>   +  return await client.get(uri);
>    }
>    ```
>    
>   @@ -125,7 +125,6 @@ Future<List<Photo>> fetchPhotos(http.Client client) async {
>      final uri = Uri.parse('https://jsonplaceholder.typicode.com/photos');
>      final response = await client.get(uri);
>    
>   -  // Use the compute function to run parsePhotos in a separate isolate.
>      return parsePhotos(response.body);
>    }
>    ```diff
>   @@ -215,14 +214,13 @@ void main() => runApp(const MyApp());
>    
>    class MyApp extends StatelessWidget {
>      const MyApp({Key? key}) : super(key: key);
>   -  static const appTitle = 'Isolate Demo';
>   -
>   +  static const _appTitle = 'Isolate Demo';
>    
>      @override
>      Widget build(BuildContext context) {
>        return const MaterialApp(
>   -      title: appTitle,
>   -      home: MyHomePage(title: appTitle),
>   +      title: _appTitle,
>   +      home: MyHomePage(title: _appTitle),
>        );
>      }
>    }
>   Error: Process completed with exit code 1.

</details>

I'm not sure what I messed up

2021-05-26 10:14 UTC, domesticmouse commented
Hey @iapicca, going from [the logs](https://github.com/flutter/website/pull/5798/checks?check_run_id=2652140997#step:12:180), I suspect you need to update some snippets. The log includes the following instructions: 

```
  Processed 388 Dart/Jade/Markdown files: 3 out of 338 fragments needed updating.
  
  Error: some code excerpts need to be refreshed. You'll need to
  rerun '/home/runner/work/website/website/tool/refresh-code-excerpts.sh' locally, and re-commit.
```

2021-05-26 14:24 UTC, iapicca commented
> going from [the logs](https://github.com/flutter/website/pull/5798/checks?check_run_id=2652140997#step:12:180), I suspect you need to update some snippets. The log includes the following instructions:
> 
> ```
>   Processed 388 Dart/Jade/Markdown files: 3 out of 338 fragments needed updating.
>   
>   Error: some code excerpts need to be refreshed. You'll need to
>   rerun '/home/runner/work/website/website/tool/refresh-code-excerpts.sh' locally, and re-commit.
> ```


when I run 'tool/refresh-code-excerpts.sh' I get this error

```console
/home/yakforward/projects/website/tool/env-set.sh: line 7: tool/shared/env-set.sh: No such file or directory
```
which makes sense since site-shared/ does not contain `tool`

```
$ ll tool
total 80
drwxrwxr-x  4 yakforward yakforward  4096 mai   16 16:02 ./
drwxrwxr-x 12 yakforward yakforward  4096 mai   16 16:02 ../
-rw-rw-r--  1 yakforward yakforward    43 mai   16 16:02 analysis_options.yaml
-rwxrwxr-x  1 yakforward yakforward   298 mai   16 16:02 before-install.sh*
-rwxrwxr-x  1 yakforward yakforward  7512 mai   16 16:02 build_check_deploy.sh*
-rwxrwxr-x  1 yakforward yakforward  1248 mai   16 16:02 check-code.sh*
drwxrwxr-x  2 yakforward yakforward  4096 mai   16 16:02 config/
drwxrwxr-x  2 yakforward yakforward  4096 mai   16 16:02 docker/
-rw-rw-r--  1 yakforward yakforward   499 mai   16 16:02 env-set.sh
-rw-rw-r--  1 yakforward yakforward  5775 mai   16 16:02 extract.dart
lrwxrwxrwx  1 yakforward yakforward    17 mai   16 16:02 install.sh -> shared/install.sh
-rw-rw-r--  1 yakforward yakforward  1559 mai   16 16:02 LICENSE
-rw-rw-r--  1 yakforward yakforward  3692 mai   16 16:02 next_prev.dart
-rw-rw-r--  1 yakforward yakforward  2602 mai   16 16:02 prdeployer.dart
-rwxrwxr-x  1 yakforward yakforward  3126 mai   16 16:02 refresh-code-excerpts.sh*
lrwxrwxrwx  1 yakforward yakforward    15 mai   16 16:02 serve.sh -> shared/serve.sh
-rwxrwxr-x  1 yakforward yakforward   223 mai   16 16:02 setup.sh*
lrwxrwxrwx  1 yakforward yakforward    20 mai   16 16:02 shared -> ../site-shared/tool/
-rw-rw-r--  1 yakforward yakforward 11788 mai   16 16:02 sitemap.txt
$ ll site-shared/
total 8
drwxrwxr-x  2 yakforward yakforward 4096 mai   16 16:02 ./
drwxrwxr-x 12 yakforward yakforward 4096 mai   16 16:02 ../
```

I'm probably missing something, as I [mentioned](https://github.com/flutter/website/pull/5798#issuecomment-842042822) I'm having hard time to understand the [instructions](https://github.com/dart-lang/site-shared/blob/master/doc/code-excerpts.md) provided

2021-05-26 22:57 UTC, domesticmouse commented
Hey @johnpryan and @miquelbeltran, can you please have a look at this PR and give some guidance? I'm out of my depth here.

2021-05-27 06:53 UTC, miquelbeltran commented
> tool/shared/env-set.sh: No such file or directory

Looks like your setup is not correct, you need to follow all the steps in the README.md (e.g. site-shared is a submodule which you need to update: https://github.com/flutter/website#2-clone-this-repo-and-its-submodules)

2021-05-27 09:57 UTC, iapicca commented
> > tool/shared/env-set.sh: No such file or directory
> 
> Looks like your setup is not correct, you need to follow all the steps in the README.md (e.g. site-shared is a submodule which you need to update: https://github.com/flutter/website#2-clone-this-repo-and-its-submodules)

@miquelbeltran 
I did not follow that before, I'll do it now

### [prerequisites](https://github.com/flutter/website#1-get-the-prerequisites)

<details>
<summary>installed nvm</summary>

> from https://github.com/nvm-sh/nvm/blob/master/README.md#installing-and-updating

```console
yakforward@yakforward-yoga720 ~ $ curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 14926  100 14926    0     0  55486      0 --:--:-- --:--:-- --:--:-- 55486
=> Downloading nvm from git to '/home/yakforward/.nvm'
=> Cloning into '/home/yakforward/.nvm'...
remote: Enumerating objects: 347, done.
remote: Counting objects: 100% (347/347), done.
remote: Compressing objects: 100% (295/295), done.
remote: Total 347 (delta 39), reused 163 (delta 27), pack-reused 0
Receiving objects: 100% (347/347), 203.77 KiB | 764.00 KiB/s, done.
Resolving deltas: 100% (39/39), done.
* (HEAD detached at FETCH_HEAD)
  master
=> Compressing and cleaning up git repository

=> Appending nvm source string to /home/yakforward/.bashrc
=> Appending bash_completion source string to /home/yakforward/.bashrc
=> Close and reopen your terminal to start using nvm or run the following to use it now:

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
yakforward@yakforward-yoga720 ~ $ export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm
yakforward@yakforward-yoga720 ~ $ source ~/.bashrc
yakforward@yakforward-yoga720 ~ $ source ~/.nvm/nvm.sh
yakforward@yakforward-yoga720 ~ $ command -v nvm
nvm
```

</details>

<details>
<summary>installed rvm</summary>

> from https://rvm.io/rvm/install#installation

```console
yakforward@yakforward-yoga720 ~ $     gpg --keyserver hkp://pool.sks-keyservers.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
gpg: key 105BD0E739499BDB: public key "Piotr Kuczynski <piotr.kuczynski@gmail.com>" imported
gpg: key 3804BB82D39DC0E3: public key "Michal Papis (RVM signing) <mpapis@gmail.com>" imported
gpg: Total number processed: 2
gpg:               imported: 2
yakforward@yakforward-yoga720 ~ $ \curl -sSL https://get.rvm.io | bash -s stable
Downloading https://github.com/rvm/rvm/archive/1.29.12.tar.gz
Downloading https://github.com/rvm/rvm/releases/download/1.29.12/1.29.12.tar.gz.asc
gpg: Signature made R 15 jaan  2021 20:46:22 EET
gpg:                using RSA key 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
gpg: Good signature from "Piotr Kuczynski <piotr.kuczynski@gmail.com>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 7D2B AF1C F37B 13E2 069D  6956 105B D0E7 3949 9BDB
GPG verified '/home/yakforward/.rvm/archives/rvm-1.29.12.tgz'
Installing RVM to /home/yakforward/.rvm/
    Adding rvm PATH line to /home/yakforward/.profile /home/yakforward/.mkshrc /home/yakforward/.bashrc /home/yakforward/.zshrc.
    Adding rvm loading line to /home/yakforward/.profile /home/yakforward/.bash_profile /home/yakforward/.zlogin.
Installation of RVM in /home/yakforward/.rvm/ is almost complete:

  * To start using RVM you need to run `source /home/yakforward/.rvm/scripts/rvm`
    in all your open shell windows, in rare cases you need to reopen all shell windows.
Thanks for installing RVM 🙏
Please consider donating to our open collective to help us maintain RVM.

👉  Donate: https://opencollective.com/rvm/donate
yakforward@yakforward-yoga720 ~ $ source ~/.rvm/bin/rvm
Ruby enVironment Manager 1.29.12 (latest) (c) 2009-2020 Michal Papis, Piotr Kuczynski, Wayne E. Seguin

Usage:
 
    rvm [--debug][--trace][--nice] <command> <options>

  for example:

    rvm list                # list installed interpreters 
    rvm list known          # list available interpreters
    rvm install <version>   # install ruby interpreter
    rvm use <version>       # switch to specified ruby interpreter
    rvm remove <version>    # remove ruby interpreter (alias: delete)
    rvm get <version>       # upgrade rvm: stable, master

Available commands:

  rvm has a number of common commands, listed below. Additional information about any command
  can be found by executing `rvm help <command>`. 

  ruby installation
      fetch                   # download binary or sources for selected ruby version
      install                 # install ruby interpreter
      list                    # show currently installed ruby interpreters
      list known              # list available interpreters
      mount                   # install ruby from external locations
      patchset                # tools related to managing ruby patchsets
      pkg                     # install a dependency package
      reinstall               # reinstall ruby and run gem pristine on all gems
      remove                  # remove ruby and downloaded sources (alias: delete)
      requirements            # installs dependencies for building ruby
      uninstall               # uninstall ruby, keeping it's sources
      upgrade                 # upgrade to another ruby version, migrating gems

  running different ruby versions
      current                 # print current ruby version and name of used gemsets
      do                      # runs a command against specified and/or all rubies
      gemdir                  # display path to current gem directory ($GEM_HOME)
      use <version>           # switch to given (and already installed) ruby version
      use default             # switch to default ruby, or system if none is set
      use system              # switch to system ruby
      wrapper                 # creates wrapper executables for a given ruby & gemset

  managing gemsets
      gemset                  # manage gemsets 
      migrate                 # migrate all gemsets from one ruby to another

  rvm configuration
      alias                   # define aliases for `rvm use`
      autolibs                # tweak settings for installing dependencies automatically 
      group                   # tools for managing groups in multiuser installations
      rvmrc                   # tools related to managing .rvmrc trust & loading gemsets

  rvm maintenance
      implode                 # removes the rvm installation completely
      cleanup                 # remove stale source files & data associated with rvm
      cron                    # manage setup for using ruby in cron
      docs                    # tools to make installing ri and rdoc docs easier
      get                     # upgrades RVM to latest head, stable or branched version
      osx-ssl-certs           # helps update OpenSSL certs installed by rvm on OS X
      reload                  # reload rvm source itself
      reset                   # remove all default and system settings
      snapshot                # backup/restore rvm installation

  troubleshooting
      config-get              # display values for RbConfig::CONFIG variables
      debug                   # additional information helping to discover issues
      export                  # set temporary env variable in the current shell
      fix-permissions         # repairs broken permissions
      repair                  # lets you repair parts of your environment, such as
                              # wr [...]

2021-05-31 05:24 UTC, domesticmouse commented
Can you please resolve conflicts? We can't land until conflicts with base are resolved.

2021-05-31 15:26 UTC, iapicca commented
unfortunately I'm be able to follow up on this PR at this moment

2021-05-31 15:26 UTC, closed without merging

2021-07-09 19:28 UTC, weriz2001 approved these changes

2021-07-09 19:29 UTC, weriz2001 approved these changes