Update Cli.md
flutter/website pull request #5869
Opened 2021-05-28 03:23 UTC by sanathusk

Since the standalone pub has been deprecated ( refer [here](https://dart.dev/tools/pub/cmd ) added instructions on how to use the pub bundled with dart instead.

2021-06-02 18:45 UTC, sfshaza2 approved these changes
Thanks for catching that!

2021-06-02 18:48 UTC, sfshaza2 commented
@sanathusk, I can't merge this PR until you sign the CLA.

2021-06-02 18:49 UTC, sfshaza2 requested changes
Approved, once CLA is signed.

2021-06-26 01:01 UTC, 69Assassin approved these changes
Sorry

2021-07-20 19:11 UTC, sfshaza2 approved these changes
LGTM

2021-08-10 22:01 UTC, sfshaza2 commented
Closing.

2021-08-10 22:01 UTC, closed without merging

2022-03-11 16:52 UTC, sanathusk commented
@googlebot I signed it!