Add go/ for next batch of deprecations
flutter/website pull request #6291
Opened 2021-09-17 20:37 UTC by Piinks

This adds a link to the list of the next deprecations we will be removing.

2021-09-17 21:05 UTC, johnpryan commented
I think this doc is private - is this intended?

2021-09-17 21:07 UTC, MrBirb commented
It seems to require an access

2021-09-17 21:10 UTC, Piinks commented
Ah thank you! Fixing now.

2021-09-17 21:13 UTC, johnpryan approved these changes

2021-09-17 21:23 UTC, Piinks commented
Thanks! I do not have permission to merge, can someone do the honors? :)

2021-09-17 21:25 UTC, johnpryan commented
FYI @sfshaza2

2021-09-18 11:46 UTC, domesticmouse approved these changes

2021-09-20 17:54 UTC, sfshaza2 commented
@Piinks, this merge will fail as it wants to merge into archived-master. Can you update it to the main branch?

2021-09-20 17:55 UTC, sfshaza2 requested changes
Change PR to use the main branch. thx

2021-09-20 18:34 UTC, sfshaza2 commented
It still says "Piinks wants to merge 1 commit into archived-master from Piinks-patch-1" at the top, @Piinks.

2021-09-20 19:04 UTC, Piinks commented
Oh cool! I did not realize that had changed. I'll open a new PR. Was this announced anywhere? I must have missed it.

2021-09-20 19:04 UTC, closed without merging

2021-09-20 19:08 UTC, Piinks commented
Oh I see how I ended up here, the link in the design doc template is associated with the master branch: https://docs.google.com/document/d/1SFRO8U2toOlAaZ38dsuEU7Wm5fn41wvBCWKiwADqfmw/edit?usp=sharing

2021-09-21 03:10 UTC, sfshaza2 commented
@Piinks, you asked if the change to the main branch had been announced. Yes, on Aug 26th, I sent email to the flutter-team saying that the website was open again, and that the README was updated with the changes. The README mentioned, right at the top, that **main** is now the default branch. But, yeah, that could be missed by folks.  :)