Breaking changes: Raw images on Web uses correct origin and colors
flutter/website pull request #6582
Opened 2021-12-16 02:20 UTC by dkwingsmt

Add migration guide: Raw images on Web uses correct origin and colors

## Presubmit checklist
- [ ] This PR doesn’t contain automatically generated corrections (Grammarly or similar).
- [ ] This PR follows the [Google Developer Documentation Style Guidelines](https://developers.google.com/style) — for example, it doesn’t use _i.e._ or _e.g._, and it avoids _I_ and _we_ (first person).
- [ ] This PR uses [semantic line breaks](https://github.com/dart-lang/site-shared/blob/master/doc/writing-for-dart-and-flutter-websites.md#semantic-line-breaks) of 80 characters or fewer.

2021-12-16 23:57 UTC, domesticmouse approved these changes
Change lgtm, please bring PR up to date with `flutter/website`'s `main` branch

2021-12-17 00:00 UTC, domesticmouse commented
This PR is failing it's link check: https://github.com/flutter/website/runs/4542509669?check_suite_focus=true#step:3:4972

Bringing the branch up to date with `flutter.website`'s `main` branch should fix this breakage

2021-12-17 00:08 UTC, domesticmouse requested changes
Removing LGTM until tests pass

2021-12-29 21:25 UTC, khanhnwin approved these changes

2021-12-30 00:13 UTC, dkwingsmt commented
@domesticmouse Can you take a look?

2021-12-31 07:48 UTC, domesticmouse approved these changes

2021-12-31 07:48 UTC, merged