More code excerpts for cookbook/persistence and cookbook/maintenance
flutter/website pull request #6719
Opened 2022-01-24 23:47 UTC by khanhnwin

_Description of what this PR is changing or adding, and why:_ Migrating more snippets to code excerpts

_Issues fixed by this PR (if any):_

## Presubmit checklist
- [x] This PR doesn’t contain automatically generated corrections (Grammarly or similar).
- [x] This PR follows the [Google Developer Documentation Style Guidelines](https://developers.google.com/style) — for example, it doesn’t use _i.e._ or _e.g._, and it avoids _I_ and _we_ (first person).
- [x] This PR uses [semantic line breaks](https://github.com/dart-lang/site-shared/blob/master/doc/writing-for-dart-and-flutter-websites.md#semantic-line-breaks) of 80 characters or fewer.

2022-01-25 00:13 UTC, domesticmouse commented on examples/development/tools/lib/hot-reload/after.dart
> +<<<<<<< HEAD
Are you meaning to check in diff markers?

2022-01-25 00:15 UTC, domesticmouse requested changes
There is a raft of diff markers in this PR. I'm guessing something went wrong somewhere

2022-01-25 00:15 UTC, domesticmouse commented on examples/development/tools/lib/hot-reload/before.dart
> +<<<<<<< HEAD
diff marker

2022-01-25 00:15 UTC, domesticmouse commented on examples/ui/assets_and_images/analysis_options.yaml
> +<<<<<<< HEAD
diff marker

2022-01-25 00:15 UTC, domesticmouse commented on examples/ui/layout/adaptive_app_demos/lib/pages/focus_examples_page.dart
> +=======
diff marker

2022-01-25 00:15 UTC, domesticmouse commented on examples/ui/layout/adaptive_app_demos/lib/widgets/extra_widget_excerpts.dart
> +<<<<<<< HEAD
diff marker

2022-01-25 00:15 UTC, domesticmouse commented on src/development/platform-integration/platform-channels.md
> +<<<<<<< HEAD
diff marker

2022-01-25 00:15 UTC, domesticmouse commented on src/development/tools/hot-reload.md
> +<<<<<<< HEAD
diff marker

2022-01-25 02:43 UTC, domesticmouse commented
Marked as draft, as @khanhnwin states in the header this is WIP

2022-01-25 17:14 UTC, khanhnwin commented
Yep, something went wrong somewhere! I need to fix. Thank you for marking as draft @domesticmouse!

2022-02-05 10:11 UTC, domesticmouse approved these changes
This looks ready to go

2022-02-07 18:25 UTC, khanhnwin commented
Closing this PR! Merged these code excerpts as part of #6785 Thanks @domesticmouse!

2022-02-07 18:25 UTC, closed without merging