Updating the banner to match the main page
flutter/website pull request #6733
Opened 2022-01-27 17:47 UTC by sfshaza2

Waiting for the main page changes (and the new page) to go live.

2022-01-27 18:18 UTC, parlough commented on src/_includes/banner.html
> +    Exciting news for Windows developers&emdash;Flutter is on the way! <a href="flutter.dev/events/flutter-update-windows">Learn more</a>
```suggestion
    Exciting news for Windows developers&emdash;Flutter is on the way! <a href="https://flutter.dev/events/flutter-update-windows">Learn more</a>
```

2022-01-27 19:30 UTC, parlough reviewed
Updating the link fixed the tests and the page seems to be live now, so looks good to me :)

2022-01-27 21:19 UTC, kwalrath commented on src/_includes/banner.html
> +    Exciting news for Windows developers&emdash;Flutter is on the way! <a href="https://flutter.dev/events/flutter-update-windows">Learn more</a>
```suggestion
    Exciting news for Windows developers—Flutter is on the way! <a href="https://flutter.dev/events/flutter-update-windows">Learn more</a>
```

2022-01-27 21:19 UTC, kwalrath commented on src/_includes/banner.html
> +    Exciting news for Windows developers&emdash;Flutter is on the way! <a href="https://flutter.dev/events/flutter-update-windows">Learn more</a>
I finally staged the PR and see this:

![image](https://user-images.githubusercontent.com/2164483/151445369-f6d36bca-fd0b-4fa7-a052-096d36f9f4a2.png)

2022-01-27 21:20 UTC, kwalrath requested changes
I think it should be `&mdash;` or `—`, not `&emdash;`.

2022-01-27 22:44 UTC, kwalrath approved these changes
Approved, assuming my change fixes the banner. (Someone please confirm if I don't have time to!)

2022-01-27 22:45 UTC, domesticmouse approved these changes

2022-01-28 00:11 UTC, domesticmouse approved these changes

2022-01-28 01:01 UTC, khanhnwin approved these changes

2022-01-28 02:06 UTC, timsneath approved these changes

2022-01-28 02:41 UTC, merged