Add migration guide for deprecating useDeleteButtonTooltip of chips
flutter/website pull request #6823
Opened 2022-02-16 19:27 UTC by RoyARG02

As title states, adds a migration guide for the change made in PR https://github.com/flutter/flutter/pull/96174.

## Presubmit checklist
- [x] This PR doesn’t contain automatically generated corrections (Grammarly or similar).
- [x] This PR follows the [Google Developer Documentation Style Guidelines](https://developers.google.com/style) — for example, it doesn’t use _i.e._ or _e.g._, and it avoids _I_ and _we_ (first person).
- [x] This PR uses [semantic line breaks](https://github.com/dart-lang/site-shared/blob/master/doc/writing-for-dart-and-flutter-websites.md#semantic-line-breaks) of 80 characters or fewer.

2022-02-17 04:01 UTC, domesticmouse approved these changes

2022-02-17 18:52 UTC, sfshaza2 requested changes
Thanks for this PR, @RoyARG02! It can use some tightening up.

2022-02-17 18:52 UTC, sfshaza2 commented on src/release/breaking-changes/chip-usedeletebuttontooltip-migration.md
> +[Deprecate `useDeleteButtonTooltip` for Chips]: {{site.repo.flutter}}/pull/96174
```suggestion
[Deprecate `useDeleteButtonTooltip` for Chips]: {{site.repo.flutter}}/pull/96174
[Flutter fix]: {{site.url}}/development/tools/flutter-fix
```

2022-02-21 06:05 UTC, RoyARG02 commented on src/release/breaking-changes/chip-usedeletebuttontooltip-migration.md
> +is provided as the message to show on the tooltip window.
Removed the reference.

2022-02-21 06:05 UTC, RoyARG02 commented on src/release/breaking-changes/chip-usedeletebuttontooltip-migration.md
> +empty string to `deleteButtonTooltipMessage`.
Removed.

2022-02-21 06:07 UTC, RoyARG02 commented
@sfshaza2 I've added in your suggestions, PTAL.

2022-02-23 18:58 UTC, sfshaza2 approved these changes
lgtm! Thanks for hanging in there, @RoyARG02!

2022-02-23 18:58 UTC, merged