Initial documentation for Windows Deployment
flutter/website pull request #6858
Opened 2022-02-28 15:44 UTC by VeArnold

_Description of what this PR is changing or adding, and why:_

The PR adds an initial Windows deployment page for Flutter Windows Desktop applications, which gives a brief overview of deployment to Microsoft Store. Similar pages already exist for macOS and Linux Desktop applications and can be expanded on.

2022-02-28 19:52 UTC, domesticmouse commented
Please sign the CLA

2022-03-01 00:13 UTC, domesticmouse reviewed
PTAL @sfshaza2

2022-03-01 00:13 UTC, domesticmouse commented on src/deployment/windows.md
> +packaging process and can not be set via the `pubspec.yaml`
We should probably document how to set this here.

Context: https://github.com/flutter/website/issues/6466

2022-03-01 00:13 UTC, domesticmouse commented on src/deployment/windows.md
> +## Updating the app's version number
Please add a section for setting an application's name.

Context: https://github.com/flutter/website/issues/6465

2022-03-01 20:30 UTC, sfshaza2 requested changes
@blasten, @VeArnold has very kindly written this new page describing how to deploy an app to the MS store. Our team (@domesticmouse) has reviewed it and made a few suggestions, but could you cast your eyes over it as well?

@VeArnold, thanks so much for doing this! Could you also add this page to the side nav? The affected file is src/_data/sidenav.yml. Thx!!

2022-03-03 04:49 UTC, domesticmouse approved these changes

2022-03-03 08:32 UTC, sfshaza2 approved these changes
lgtm!

2022-03-03 08:32 UTC, merged