Update firebase.json
flutter/website pull request #6884
Opened 2022-03-07 19:27 UTC by Jasguerrero

_Description of what this PR is changing or adding, and why:_

_Issues fixed by this PR (if any):_

## Presubmit checklist
- [ ] This PR doesn’t contain automatically generated corrections (Grammarly or similar).
- [ ] This PR follows the [Google Developer Documentation Style Guidelines](https://developers.google.com/style) — for example, it doesn’t use _i.e._ or _e.g._, and it avoids _I_ and _we_ (first person).
- [ ] This PR uses [semantic line breaks](https://github.com/dart-lang/site-shared/blob/main/doc/writing-for-dart-and-flutter-websites.md#semantic-line-breaks) of 80 characters or fewer.

2022-03-07 20:01 UTC, sfshaza2 requested changes
Hi, @Jasguerrero! Please fill out the template doc. We need that in place before we land the PR. And please move this to draft status.

2022-04-04 18:09 UTC, sfshaza2 reviewed
This page looks well under way. Could you change the title of the doc? And take this PR out of draft, so I can land it? Thx!

2022-04-06 16:03 UTC, Jasguerrero commented
> This page looks well under way. Could you change the title of the doc? And take this PR out of draft, so I can land it? Thx!

@sfshaza2 I am still waiting on feedback for my design doc. As soon as I get I will be updating the PR. Thank you!

2022-04-22 18:19 UTC, Jasguerrero commented
@sfshaza2 the design doc is ready. You can merge it now

2022-04-22 18:48 UTC, sfshaza2 approved these changes
lgtm!

2022-04-22 18:48 UTC, merged