Update implicit animations page to use current code examples
flutter/website pull request #6927
Opened 2022-03-16 14:42 UTC by micpap25

Fixes the implicit animation page's linting error by updating the iframe code to use the correct starter / complete code from the examples folder. 
Fixes #6897

2022-03-16 21:24 UTC, domesticmouse requested changes
Please drop the copyright headers. Otherwise, LGTM

2022-03-16 21:24 UTC, domesticmouse commented on src/_includes/docs/implicit-animations/shape-shifting-starter-code.md
> +// Copyright 2019 the Dart project authors. All rights reserved.
We probably don't need the copyright headers in the published code

2022-03-16 21:24 UTC, domesticmouse commented on src/_includes/docs/implicit-animations/shape-shifting-complete.md
> +// Copyright 2019 the Dart project authors. All rights reserved.
ditto

2022-03-16 21:24 UTC, domesticmouse commented on src/_includes/docs/implicit-animations/fade-in-starter-code.md
> +// Copyright 2019 the Dart project authors. All rights reserved.
ditto

2022-03-16 21:24 UTC, domesticmouse commented on src/_includes/docs/implicit-animations/fade-in-complete.md
> +// Copyright 2019 the Dart project authors. All rights reserved.
ditto

2022-03-16 22:33 UTC, micpap25 commented
Hi, I'll drop them when I get the chance. Should I then also drop them from the diffs on the rest of the page?

2022-03-17 03:02 UTC, domesticmouse commented
> Hi, I'll drop them when I get the chance. Should I then also drop them from the diffs on the rest of the page?

Yes please!

2022-03-17 18:16 UTC, sfshaza2 commented
Thanks for updating this, @micpap25!

2022-03-18 15:22 UTC, micpap25 commented
I made the updates; I can't tell what's causing the copyright headers to show up in the diffs. The comment below the copyright header is necessary though.

2022-03-18 23:20 UTC, domesticmouse commented
@khanhnwin can you help plz?

2022-03-21 21:29 UTC, khanhnwin commented
hey y'all - I don't seem to see the Copyright text in the diffs anymore. Am I missing something?

2022-03-22 22:25 UTC, parlough commented
@domesticmouse's review comments on those lines will still show the headers from previous commits, but they are no longer there in the actual diff. I've gone ahead and resolved the outdated comments.

Looks good to me!

2022-03-23 01:14 UTC, domesticmouse approved these changes

2022-03-23 01:15 UTC, merged