Updating info on Windows version support
flutter/website pull request #7187
Opened 2022-05-24 23:33 UTC by sfshaza2

At @timsneath's request.

2022-05-24 23:35 UTC, domesticmouse approved these changes
Ptal @cbracken

2022-05-24 23:36 UTC, timsneath commented on src/get-started/install/windows.md
> +- **Operating Systems**: Windows 10 SP1 or later (64-bit), x86-64 based.
Windows 10 or later (not Windows 10 SP1 or later).

2022-05-24 23:37 UTC, timsneath requested changes
Not SP1 :)

2022-05-25 00:13 UTC, domesticmouse approved these changes

2022-05-25 00:14 UTC, domesticmouse commented
Looks like the snippets need to be refreshed

2022-05-25 00:38 UTC, cbracken approved these changes
lgtm; thanks!

2022-05-25 16:33 UTC, sfshaza2 commented
@timsneath can you approve the changes? Only the person who requested changes can approve them.

2022-05-25 17:09 UTC, timsneath approved these changes

2022-05-25 17:09 UTC, merged

2022-05-25 17:21 UTC, sfshaza2 commented
Thx, @timsneath!