Add go/dash-xcode-plan-brief
flutter/website pull request #7206
Opened 2022-05-27 16:09 UTC by nuritzi

Add a go link for the xcode brief

Apple releases a new major release of Xcode version at least once a year, with smaller updates throughout the year. Each time there is a new update, the Flutter team must include the updated version in their SDK. This brief talks about the challenges we face updating Xcode each time and will propose a way to improve.

## Presubmit checklist
- [X] This PR doesn’t contain automatically generated corrections (Grammarly or similar).
- [X] This PR follows the [Google Developer Documentation Style Guidelines](https://developers.google.com/style) — for example, it doesn’t use _i.e._ or _e.g._, and it avoids _I_ and _we_ (first person).
- [X] This PR uses [semantic line breaks](https://github.com/dart-lang/site-shared/blob/master/doc/writing-for-dart-and-flutter-websites.md#semantic-line-breaks) of 80 characters or fewer.

2022-05-27 16:09 UTC, nuritzi commented
@Sfshaza can you please review this go link when you have a chance? (or anyone else)

2022-05-28 02:44 UTC, domesticmouse approved these changes

2022-05-30 22:26 UTC, sfshaza2 requested changes
@nuritzi, which is "dash" in the URL? It doesn't seem relevant, so can you remove it?

2022-06-17 15:55 UTC, sfshaza2 commented
@nuritzi, I'm going to close this PR for now. Please re-open (or create a new one) when you are ready.

2022-06-17 15:55 UTC, closed without merging

2022-06-23 23:36 UTC, nuritzi commented
Yes, let's close it out. Thanks, Shams!!