Fixed Dart info
flutter/website pull request #7208
Opened 2022-05-28 02:17 UTC by zarif25

_Description of what this PR is changing or adding, and why:_

_Issues fixed by this PR (if any):_ Fixed the Dart info that says, "Sort child properties last in widget instance creations"

## Presubmit checklist
- [x] This PR doesn’t contain automatically generated corrections (Grammarly or similar).
- [x] This PR follows the [Google Developer Documentation Style Guidelines](https://developers.google.com/style) — for example, it doesn’t use _i.e._ or _e.g._, and it avoids _I_ and _we_ (first person).
- [x] This PR uses [semantic line breaks](https://github.com/dart-lang/site-shared/blob/master/doc/writing-for-dart-and-flutter-websites.md#semantic-line-breaks) of 80 characters or fewer.

2022-05-28 02:46 UTC, domesticmouse commented
I believe this is a code excerpt, so you’ll also need to update the source that this sample is excerpted from.

2022-05-28 08:07 UTC, domesticmouse requested changes

2022-05-28 08:07 UTC, domesticmouse commented on src/development/ui/widgets-intro.md
> +        child: Icon(Icons.add),
Please modify the code in `lib/main_tutorial.dart` and then run the `snippets` tooling per the `README.md`.

2022-07-10 00:53 UTC, parlough commented
This was fixed alongside some other changes in https://github.com/flutter/website/pull/7335, so I'm going to close this. 

Thanks again for the pull request though!

2022-07-10 00:53 UTC, closed without merging