Update ios.md
flutter/website pull request #7305
Opened 2022-06-24 13:05 UTC by serifsadi

Add missing information about export an IPA with 'flutter build ipa' command.

_Description of what this PR is changing or adding, and why:_

_Issues fixed by this PR (if any):_

## Presubmit checklist
- [ ] This PR doesn’t contain automatically generated corrections (Grammarly or similar).
- [ ] This PR follows the [Google Developer Documentation Style Guidelines](https://developers.google.com/style) — for example, it doesn’t use _i.e._ or _e.g._, and it avoids _I_ and _we_ (first person).
- [ ] This PR uses [semantic line breaks](https://github.com/dart-lang/site-shared/blob/master/doc/writing-for-dart-and-flutter-websites.md#semantic-line-breaks) of 80 characters or fewer.

2022-06-24 18:34 UTC, sfshaza2 commented on src/deployment/ios.md
> +{{site.alert.end}}
```suggestion
{{site.alert.note}}
  Running the `flutter build ipa` command without specifying
  a `.plist` file only generates an `.xarchive` file.
  To export an IPA, create a new file called `ExportOptions.plist`
  and run the command with
  `--export-options-plist=ios/ExportOptions.plist`.
  See`xcodebuild -h` for available `exportOptionsPlist` keys.
{{site.alert.end}}
```

2022-06-24 18:36 UTC, sfshaza2 reviewed
lgtm (though I did massage the text).  @jmagman, did you want to confirm?

2022-06-24 18:53 UTC, serifsadi commented on src/deployment/ios.md
> +{{site.alert.end}}
Very neat touch! Thanks.

2022-06-27 20:34 UTC, jmagman reviewed
This isn't true as of https://github.com/flutter/flutter/pull/97672 which is available in stable.  Instead of this documentation change, can you file a GitHub issue that describes the issue you're seeing?

2022-06-27 20:35 UTC, jmagman requested changes
Meant to request changes

2022-07-27 20:21 UTC, khanhnwin commented
Hey @serifsadi any updates on these changes? Thanks!

2022-07-27 21:05 UTC, jmagman commented
Closing this, I don't believe this note should be necessary, and if it is I'd first like to see a bug report describing the issue so we can come up with a fix and/or workaround.

2022-07-27 21:05 UTC, closed without merging