fixing broken link
flutter/website pull request #7308
Opened 2022-06-25 01:23 UTC by sfshaza2

Fixes https://github.com/flutter/website/issues/7307

2022-06-25 01:24 UTC, domesticmouse approved these changes

2022-06-25 22:26 UTC, parlough requested changes

2022-06-25 22:26 UTC, parlough commented on src/development/tools/hot-reload.md
>  In Dart, [static fields are lazily initialized][const-new].
The const-final portion of the language tour doesn't talk about this like the article did, so we should adjust this piece to link elsewhere in the tour. I've made this and one other comment to include those changes:

```suggestion
In Dart, [static fields are lazily initialized][static-variables].
```

2022-06-25 22:26 UTC, parlough commented on src/development/tools/hot-reload.md
```suggestion
[static-variables]: {{site.dart-site}}/guides/language/language-tour#static-variables
```

2022-06-26 19:16 UTC, sfshaza2 commented
Hey, @parlough. Yeah, I realized that the old link has info not covered in the tour. I simultaneously reached out to @munificent on Friday to ask if we can add the info from that old link. I'm not sure why it wasn't ever added to the tour (or somewhere else on dart.dev). Your suggestion to link to static vars is a good one and I've committed that.

@domesticmouse, can you approve?

2022-06-26 19:16 UTC, parlough approved these changes

2022-06-26 22:50 UTC, merged