Update deep-linking.md
flutter/website pull request #7811
Opened 2022-11-11 21:18 UTC by chunhtai

_Description of what this PR is changing or adding, and why:_

_Issues fixed by this PR (if any):_ Fixes #ISSUE-NUMBER

## Presubmit checklist
- [ ] This PR doesn’t contain automatically generated corrections (Grammarly or similar).
- [ ] This PR follows the [Google Developer Documentation Style Guidelines](https://developers.google.com/style) — for example, it doesn’t use _i.e._ or _e.g._, and it avoids _I_ and _we_ (first person).
- [ ] This PR uses [semantic line breaks](https://github.com/dart-lang/site-shared/blob/main/doc/writing-for-dart-and-flutter-websites.md#semantic-line-breaks) of 80 characters or fewer.

2022-11-13 02:35 UTC, domesticmouse approved these changes

2022-11-13 03:21 UTC, sfshaza2 approved these changes
lgtm

2022-11-13 03:32 UTC, atsansone commented on src/development/ui/navigation/deep-linking.md
> +name is `com.example.myflutterapp`, the command will then be:
**issue:** Need to capitalize Android and use active voice in the second sentence.
```suggestion
Replace the `<package name>` with the package name of your Android app.
If you named the package `com.example.myflutterapp`, run the following command:
```

2022-11-13 03:32 UTC, atsansone requested changes
@chunhtai : Two small issues, then it should be ready to merge.

2022-11-14 16:37 UTC, chunhtai commented
> @chunhtai : Two small issues, then it should be ready to merge.

Thanks I committed your suggestions.

2022-11-14 21:15 UTC, atsansone approved these changes

2022-11-14 21:21 UTC, merged