Updating project setup to make steps more clear
flutter/website pull request #7955
Opened 2022-12-18 05:01 UTC by 2020009-CPE

_Description of what this PR is changing or adding, and why:_

_Issues fixed by this PR (if any):_ Fixes #ISSUE-NUMBER

## Presubmit checklist
- [ ] This PR doesn’t contain automatically generated corrections (Grammarly or similar).
- [ ] This PR follows the [Google Developer Documentation Style Guidelines](https://developers.google.com/style) — for example, it doesn’t use _i.e._ or _e.g._, and it avoids _I_ and _we_ (first person).
- [ ] This PR uses [semantic line breaks](https://github.com/dart-lang/site-shared/blob/main/doc/writing-for-dart-and-flutter-websites.md#semantic-line-breaks) of 80 characters or fewer.
- [ ] This PR doesn’t contain automatically generated corrections (Grammarly or similar).
- [ ] This PR doesn’t contain automatically generated corrections (Grammarly or similar).

2022-12-18 05:14 UTC, domesticmouse requested changes

2022-12-18 05:14 UTC, domesticmouse commented on src/development/add-to-app/ios/project-setup.md
> +
Please trim trailing white space here and on following lines

2022-12-21 06:59 UTC, sfshaza2 commented
@jmagman, this PR needs wordsmithing and re-formatting but, before I dive into that, can you verify the changes?

2022-12-21 07:00 UTC, sfshaza2 commented
Also, @2020009-CPE, I can't land this without you signing the CLA.

2022-12-21 18:56 UTC, jmagman requested changes
@2020009-CPE Please fill out the description template as requested, particularly "Description of what this PR is changing or adding, and why:".  Can you give us a summary of what issues you hit and how the current documentation is unclear?  

Please also revert unnecessary whitespace changes as @domesticmouse suggested to make it easier to see what you actually changed.

2023-01-09 13:10 UTC, parlough commented
It looks like these changes landed as part of https://github.com/flutter/website/pull/7828 by the original author of the attached commit.

Thanks for opening the PR though and let us know if you'd like to see any further changes or updates to the page, thanks!

2023-01-09 13:10 UTC, closed without merging