Remove outdated pages
flutter/website pull request #7970
Opened 2022-12-20 19:24 UTC by jmagman

_Description of what this PR is changing or adding, and why:_ Remove outdated pages. These listings are no longer open.

## Presubmit checklist
- [x] This PR doesn’t contain automatically generated corrections (Grammarly or similar).
- [x] This PR follows the [Google Developer Documentation Style Guidelines](https://developers.google.com/style) — for example, it doesn’t use _i.e._ or _e.g._, and it avoids _I_ and _we_ (first person).
- [x] This PR uses [semantic line breaks](https://github.com/dart-lang/site-shared/blob/main/doc/writing-for-dart-and-flutter-websites.md#semantic-line-breaks) of 80 characters or fewer.

2022-12-20 22:19 UTC, sfshaza2 requested changes
These files are not being displayed currently. Why do we need to remove them from the repo? Is it a case of people following these links and finding the pages? If so, I prefer a different solution. I would, for now, add a redirect that goes to a "we are not currently hiring." page.

2022-12-20 22:19 UTC, sfshaza2 commented on src/_includes/banner.html
> -    {% endcomment %}
This is already commented out, so it doesn't even show up in the HTML as a comment. I feel no need to delete it.

2022-12-20 23:21 UTC, jmagman commented
> These files are not being displayed currently. 

I navigated to them from https://docs.flutter.dev/jobs. I guess why would we not remove them from the repository since it's source controlled and we can bring it back whenever we want?

However you want to solve this is fine, but those postings should be removed.

2022-12-22 15:34 UTC, sfshaza2 commented
Closing. Replaced by PR https://github.com/flutter/website/pull/7973

2022-12-22 15:34 UTC, closed without merging

2022-12-22 19:53 UTC, jmagman commented
Thanks @sfshaza2!