FIx #2654, #2709
flutter/website pull request #8169
Opened 2023-01-28 23:17 UTC by wurikiji

_Description of what this PR is changing or adding, and why:_

When you declare font in your own app package, you should omit `package` property from the `TextStyle`. 

_Issues fixed by this PR (if any):_

#2654, #2709

## Presubmit checklist
- [x] This PR doesn’t contain automatically generated corrections (Grammarly or similar).
- [x] This PR follows the [Google Developer Documentation Style Guidelines](https://developers.google.com/style) — for example, it doesn’t use _i.e._ or _e.g._, and it avoids _I_ and _we_ (first person).
- [x] This PR uses [semantic line breaks](https://github.com/dart-lang/site-shared/blob/master/doc/writing-for-dart-and-flutter-websites.md#semantic-line-breaks) of 80 characters or fewer.

2023-01-28 23:20 UTC, domesticmouse approved these changes

2023-01-29 02:21 UTC, domesticmouse requested changes

2023-01-29 02:21 UTC, domesticmouse commented on src/cookbook/design/package-fonts.md
> -    package: 'awesome_package',
This snippet is extracted from a project. You'll need to update the related project for the snippets check to pass.

2023-01-29 05:29 UTC, domesticmouse approved these changes
Good to land once CI turns green

2023-01-30 16:44 UTC, sfshaza2 approved these changes
lgtm!

2023-01-30 16:44 UTC, merged