Fixes a potential success even if no-op in test.
flutter/website pull request #8207
Opened 2023-02-04 04:15 UTC by nohe427

_Description of what this PR is changing or adding, and why:_

This fixes a potential success in the test which could happen if the cart.add method fails to call
notifyListeners(). This just uses a simple interger counter. A better implementation would be to use the mockito package: https://pub.dev/packages/mockito however, I was attempting to keep the sample simple.

_Issues fixed by this PR (if any):_
Fixes [PAGE ISSUE]: 'Simple app state management' #8135

## Presubmit checklist
- [x] This PR doesn’t contain automatically generated corrections (Grammarly or similar).
- [x] This PR follows the [Google Developer Documentation Style Guidelines](https://developers.google.com/style) — for example, it doesn’t use _i.e._ or _e.g._, and it avoids _I_ and _we_ (first person).
- [x] This PR uses [semantic line breaks](https://github.com/dart-lang/site-shared/blob/master/doc/writing-for-dart-and-flutter-websites.md#semantic-line-breaks) of 80 characters or fewer.

2023-02-04 05:06 UTC, domesticmouse requested changes
This is an excerpt from a dart file. This PR will fail CI until the related file is also changed 😏

2023-02-04 06:14 UTC, nohe427 commented
Forgot to read the `README`. I should be all set now.

2023-02-05 05:53 UTC, domesticmouse approved these changes

2023-02-05 05:54 UTC, domesticmouse commented
Good to land once CI turns green

2023-02-06 05:40 UTC, merged