Adds migration guide for material localized Strings
flutter/website pull request #8543
Opened 2023-04-12 22:40 UTC by chunhtai

https://github.com/flutter/flutter/pull/124711

## Presubmit checklist
- [ ] This PR doesn’t contain automatically generated corrections (Grammarly or similar).
- [ ] This PR follows the [Google Developer Documentation Style Guidelines](https://developers.google.com/style) — for example, it doesn’t use _i.e._ or _e.g._, and it avoids _I_ and _we_ (first person).
- [ ] This PR uses [semantic line breaks](https://github.com/dart-lang/site-shared/blob/master/doc/writing-for-dart-and-flutter-websites.md#semantic-line-breaks) of 80 characters or fewer.

2023-04-13 17:56 UTC, khanhnwin commented
Thanks @chunhtai! Would you mind if we moved those dart code samples to a project in the examples/ directory so that we can import them as snippets?

2023-04-13 18:01 UTC, chunhtai commented
I am not sure how this would work, some of the code in the snippet may be broken once the change is landed

2023-04-14 18:06 UTC, chunhtai commented
a friendly bump.

2023-04-16 18:58 UTC, sfshaza2 requested changes
@chunhtai, a few changes. Also, @khanhnwin, can you help @chunhtai with the code snippets, or maybe we don't need it? I defer to you.

2023-04-16 18:58 UTC, sfshaza2 commented on src/release/breaking-changes/material-localized-strings.md
> +instead.
```suggestion
If you use these strings in your code,
you can access them from `WidgetsLocalizations`instead.
```

2023-04-16 18:58 UTC, sfshaza2 commented on src/release/breaking-changes/material-localized-strings.md
> +subclass.
```suggestion
If you override `MaterialLocalizations` or `WidgetsLocalizations`,
make sure to remove the translations from the `MaterialLocalizations`
subclass and move them to the `WidgetsLocalizations` subclass.
```

2023-04-16 18:58 UTC, sfshaza2 commented on src/release/breaking-changes/material-localized-strings.md
> +Landed in version: TBD  <br>
@chunhtai, can you fill this TBD out?

2023-04-16 18:58 UTC, sfshaza2 commented on src/release/breaking-changes/material-localized-strings.md
> +}
Add "Code after migration" text here, and complete the two resulting Dart code blocks.

2023-04-18 17:08 UTC, chunhtai commented
a friendly bump

2023-04-20 00:37 UTC, khanhnwin reviewed
Let's land this and then I can move the code out to an examples project!

2023-04-20 00:37 UTC, khanhnwin commented on src/release/breaking-changes/material-localized-strings.md
> +class MaterialLocalizationsMyLanguage extends MaterialLocalizationsEn {
Does this class need to remain here after we've moved the reorderItemRight getter?

2023-04-20 16:18 UTC, khanhnwin approved these changes

2023-04-20 17:59 UTC, khanhnwin commented
Good to land if it looks good to you @sfshaza2

2023-04-20 18:01 UTC, sfshaza2 approved these changes
lgtm!

2023-04-20 18:02 UTC, merged