Deprecate `describeEnum`.
flutter/website pull request #8571
Opened 2023-04-18 04:26 UTC by bernaferrari

Tied to https://github.com/flutter/flutter/pull/125016

2023-04-19 18:17 UTC, sfshaza2 commented on src/release/breaking-changes/describeEnum-migration.md
> +Landed in version: TBD<br>
Please fill out this TBD with the info on when this landed.

2023-04-19 18:18 UTC, sfshaza2 requested changes
Hi, @bernaferrari! Thanks for this PR! Can you also add this breaking change to the index file?

2023-04-25 23:25 UTC, sfshaza2 approved these changes
lgtm

2023-04-25 23:46 UTC, merged

2023-04-25 23:47 UTC, bernaferrari commented
(should this be merged? The original code/official change hasn't landed yet, might take a few days/weeks still)