Fix typo "priori" -> "prior"
flutter/website pull request #8573
Opened 2023-04-18 09:43 UTC by satwanjyu

_Description of what this PR is changing or adding, and why:_

_Issues fixed by this PR (if any): Fix typo in `src/resources/inside-flutter.md:589`

## Presubmit checklist
- [x] This PR doesn’t contain automatically generated corrections (Grammarly or similar).
- [x] This PR follows the [Google Developer Documentation Style Guidelines](https://developers.google.com/style) — for example, it doesn’t use _i.e._ or _e.g._, and it avoids _I_ and _we_ (first person).
- [x] This PR uses [semantic line breaks](https://github.com/dart-lang/site-shared/blob/master/doc/writing-for-dart-and-flutter-websites.md#semantic-line-breaks) of 80 characters or fewer.

2023-04-18 09:51 UTC, domesticmouse commented
PTAL @sfshaza2

2023-04-18 09:54 UTC, domesticmouse requested changes

2023-04-25 20:42 UTC, sfshaza2 commented on src/resources/inside-flutter.md
> +`lerp` function cannot have a prior knowledge of all the possible types,
```suggestion
`lerp` function can't anticipate all possible types,
```

2023-04-25 20:43 UTC, sfshaza2 commented on src/resources/inside-flutter.md
> -`lerp` function cannot have a priori knowledge of all the possible types,
Yeah, it's better to avoid the Latin altogether.

2023-04-25 20:44 UTC, sfshaza2 approved these changes
Thanks for pointing this confusing text out, @satwanjyu! lgtm

2023-04-25 21:55 UTC, domesticmouse approved these changes

2023-04-25 21:56 UTC, merged