Add `TabBar.tabAlignment` migration guide
flutter/website pull request #8700
Opened 2023-05-17 14:22 UTC by TahaTesser

fixes https://github.com/flutter/flutter/issues/126920

[TabBar.tabAlignment](https://master-api.flutter.dev/flutter/material/TabBar/tabAlignment.html) was introduced in https://github.com/flutter/flutter/pull/125036

This PR adds a  migration guide for `TabBar.tabAlignment`.

Related https://github.com/flutter/flutter/pull/125974

## Presubmit checklist

- x ] This PR doesn’t contain automatically generated corrections (Grammarly or similar).
- [x] This PR follows the [Google Developer Documentation Style Guidelines](https://developers.google.com/style) — for example, it doesn’t use _i.e._ or _e.g._, and it avoids _I_ and _we_ (first person).
- [x] This PR uses [semantic line breaks](https://github.com/dart-lang/site-shared/blob/main/doc/writing-for-dart-and-flutter-websites.md#semantic-line-breaks) of 80 characters or fewer.

2023-05-19 18:37 UTC, Piinks commented on src/release/breaking-changes/tab-alignment.md
> +The `TabBar.tabAlignment` property is introduced to customize the alignment of tabs in a Material 3 `TabBar`. The `TabAlignment` enum has the following values:
```suggestion
The `TabBar.tabAlignment` property was introduced to customize the alignment of tabs in a Material 3 `TabBar`. The `TabAlignment` enum has the following values:
```

2023-05-19 18:38 UTC, Piinks commented on src/release/breaking-changes/tab-alignment.md
> +* `TabAlignment.fill`: Aligns the tabs to the start and stretches the tabs to fill the fixed `TabBar`.
Should these descriptions also mention which ones work with `isScrollable` and which ones don't?

2023-05-19 18:38 UTC, Piinks reviewed
This is great! Just a couple of small nits

2023-05-22 03:50 UTC, atsansone requested changes
@TahaTesser : A few changes for length and semantic breaks. Thanks!

2023-05-22 03:50 UTC, atsansone commented on src/release/breaking-changes/tab-alignment.md
> +A Material 3 scrollable `TabBar` uses `TabAlignment.startOffset` as the default tab alignment which aligns the tabs to the start of the scrollable `TabBar` with an offset of `52.0` pixels.
**issues:** 
- Write as shorter sentences per [GSG](https://developers.google.com/style/accessibility#ease-of-reading).
- Use [semantic breaks](https://sembr.org).

```suggestion
A Material 3 scrollable `TabBar` uses `TabAlignment.startOffset` as the default tab alignment.
This aligns the tabs to the start of the scrollable `TabBar` with an offset of `52.0` pixels.
```

2023-05-22 03:50 UTC, atsansone commented on src/release/breaking-changes/tab-alignment.md
> +The following code snippets show how to use `TabBar.tabAlignment` to align the tabs to the start of the scrollable `TabBar`:
**issues:** 
- Write as shorter sentences per [GSG](https://developers.google.com/style/accessibility#ease-of-reading).
- Use [semantic breaks](https://sembr.org).

```suggestion
To align the tabs to the start of the scrollable `TabBar`, set `TabBar.tabAlignment` to `TabAlignment.start`.
This change also removes the `52.0` pixel offset.
The following code snippets show how to use `TabBar.tabAlignment` to align the tabs
to the start of the scrollable `TabBar`:
```

2023-05-22 10:45 UTC, TahaTesser commented
@atsansone 
Appreciate the review, made the requested changes

2023-05-24 22:02 UTC, Piinks commented on src/release/breaking-changes/tab-alignment.md
> +To change this alignment, set the `TabBar.tabAlignment` property.
You can also use the theme, correct?

2023-05-25 12:37 UTC, TahaTesser commented on src/release/breaking-changes/tab-alignment.md
> +To change this alignment, set the `TabBar.tabAlignment` property.
That's right.

2023-05-25 14:12 UTC, atsansone approved these changes
@TahaTesser : I'll approve this as is. Keep in mind for next time that we hard wrap lines at 80 characters. Thanks!

2023-05-26 19:16 UTC, merged