Remove android info and add limitations
flutter/website pull request #8793
Opened 2023-05-31 21:21 UTC by leighajarett

_Description of what this PR is changing or adding, and why:_
Removing the bit about Android and adding in some limitations mentioned by @cyanglaz 

_Issues fixed by this PR (if any):_ https://github.com/flutter/website/issues/8741

## Presubmit checklist

- [x] This PR doesn’t contain automatically generated corrections (Grammarly or similar).
- [x] This PR follows the [Google Developer Documentation Style Guidelines](https://developers.google.com/style) — for example, it doesn’t use _i.e._ or _e.g._, and it avoids _I_ and _we_ (first person).
- [x] This PR uses [semantic line breaks](https://github.com/dart-lang/site-shared/blob/main/doc/writing-for-dart-and-flutter-websites.md#semantic-line-breaks) of 80 characters or fewer.

2023-05-31 21:46 UTC, sfshaza2 requested changes
Hi, @leighajarett! I did much of the review on this page before noticing that you made this PR under our old information architecture. The new location for this file is: /src/platform-integration/ios/platform-views.md.

Can you make the edits that I've provided and also merge with the current repo so that it's in the correct place?

2023-05-31 21:46 UTC, sfshaza2 commented on src/development/platform-integration/ios/platform-views.md
> +and add the following build implementation,
Don't need "following" twice in the same sentence.

```suggestion
and add the build implementation,
```

2023-05-31 21:46 UTC, sfshaza2 commented on src/development/platform-integration/ios/platform-views.md
> +do the following in `native_view_example.dart`:
```suggestion
In the Dart widget file, make changes similar to those
show in `native_view_example.dart`:
```

2023-05-31 21:46 UTC, sfshaza2 commented on src/development/platform-integration/ios/platform-views.md
> +  // This is used in the platform side to register the view.
```suggestion
  // Use this on the platform side to register the view.
```

2023-05-31 21:46 UTC, sfshaza2 commented on src/development/platform-integration/ios/platform-views.md
> +On the platform side, you use the either Swift or Objective-C:
```suggestion
On the platform side  use either Swift or Objective-C:
```

2023-05-31 21:46 UTC, sfshaza2 commented on src/development/platform-integration/ios/platform-views.md
> +For example, `FLNativeView.swift`:
```suggestion
For example, as shown in `FLNativeView.swift`:
```

2023-05-31 21:46 UTC, sfshaza2 commented on src/development/platform-integration/ios/platform-views.md
> +Add the headers for the factory and the platform view.
```suggestion
In Objective-C, add the headers for the factory and the platform view.
```

2023-05-31 21:46 UTC, sfshaza2 commented on src/development/platform-integration/ios/platform-views.md
> +to detect the platform, and decide what widget to use:
```suggestion
to detect the platform, and decide which widget to use:
```

2023-05-31 21:46 UTC, sfshaza2 commented on src/development/platform-integration/ios/platform-views.md
> +  // This is used in the platform side to register the view.
```suggestion
  // Use this on the platform side to register the view.
```

2023-05-31 21:46 UTC, sfshaza2 requested changes
Hi, @leighajarett! I did much of the review on this page before noticing that you made this PR under our old information architecture. The new location for this file is: /src/platform-integration/ios/platform-views.md.

Can you make the edits that I've provided and also merge with the current repo so that it's in the correct place?

2023-06-02 00:26 UTC, domesticmouse approved these changes

2023-06-02 00:26 UTC, domesticmouse commented on src/development/platform-integration/ios/platform-views.md
> +iOS only uses Hybrid composition,
suggestion: "iOS uses only hybrid composition"

Also, hybrid composition doesn't appear to be defined on this page before this mention. Can we link to the definition, or should we lose the use of this undefined term?

2023-06-02 00:26 UTC, domesticmouse commented on src/development/platform-integration/ios/platform-views.md
> +capped at 80fps to avoid rendering janks.
I'm curious why 80fps was chosen. 60fps and 90fps seem sane, but 80?

2023-06-05 14:23 UTC, leighajarett commented
This got messy with moving to new information architecture so moving to a new PR

2023-06-05 14:23 UTC, closed without merging