Added alternative way to store keystore passwords for macOS users
flutter/website pull request #8818
Opened 2023-06-01 22:03 UTC by sonnyvesali

_Description of what this PR is changing or adding, and why:_
Added a site note including the link to a blog post that shows macOS users how they can store keystore passwords in the Keychain app instead of plain text.
_Issues fixed by this PR (if any):_

## Presubmit checklist

- [ X] This PR doesn’t contain automatically generated corrections (Grammarly or similar).
- [ X] This PR follows the [Google Developer Documentation Style Guidelines](  c) — for example, it doesn’t use _i.e._ or _e.g._, and it avoids _I_ and _we_ (first person).
- [ X] This PR uses [semantic line breaks](https://github.com/dart-lang/site-shared/blob/main/doc/writing-for-dart-and-flutter-websites.md#semantic-line-breaks) of 80 characters or fewer.

2023-06-02 03:44 UTC, parlough commented
Thanks for opening a pull request! However, before we can take a look and review it, you'll need to sign the CLA as outlined at https://github.com/flutter/website/pull/8818/checks?check_run_id=13941071948. Let us know if you have any issues, thanks!

2023-06-02 10:37 UTC, sonnyvesali commented
> Thanks for opening a pull request! However, before we can take a look and review it, you'll need to sign the CLA as outlined at https://github.com/flutter/website/pull/8818/checks?check_run_id=13941071948. Let us know if you have any issues, thanks!

@parlough I tried signing it but it won't let me put a non-google email and my github is under a non-google account, how can I get around this obstacle?

2023-06-02 10:52 UTC, sonnyvesali commented
> Thanks for opening a pull request! However, before we can take a look and review it, you'll need to sign the CLA as outlined at https://github.com/flutter/website/pull/8818/checks?check_run_id=13941071948. Let us know if you have any issues, thanks!

@parlough is it not possible to sign the CLA with a non-google github account? I used my gmail and then put my GH username, I'm not sure it fixed it, lmk what else I need / can do.

2023-06-02 16:04 UTC, sfshaza2 requested changes
Please make these minor changes and I can lgtm.

2023-06-02 16:04 UTC, sfshaza2 commented on src/deployment/android.md
> +  file and follow the steps in the link above accordingly.
```suggestion
  If you'd prefer not to store your passwords in plain text,
  you can store your credentials in the [Keychain Access App][].
  In this case, skip the first 2 lines of `key.properties`
  file and follow the steps in the Pilloxa link.
```

2023-06-02 16:48 UTC, sfshaza2 commented
@sonnyvesali, the CLA test is looking for a signature from:  sonny.vesali@proton.me. It seems that your account isn't set up properly.

2023-06-27 19:50 UTC, sfshaza2 commented
Did we lose you, @sonnyvesali? I'm sorry about the confusion with the CLA.

2023-09-11 17:39 UTC, parlough commented
Thanks again for the pull request!

As mentioned earlier, you'll need to sign the CLA with the proton email for us to take a look. Sorry about the confusion, but let us know if you need any help doing so :) 

I'll close this for now, but feel free to reopen once you sign the CLA or open a new PR. Thanks!

2023-09-11 17:39 UTC, closed without merging