Remove Android bits and add limitations on ios platform views
flutter/website pull request #8833
Opened 2023-06-05 14:24 UTC by leighajarett

Moving from previous PR: https://github.com/flutter/website/pull/8793

Fixes https://github.com/flutter/website/issues/8741

## Presubmit checklist

- [x] This PR doesn’t contain automatically generated corrections (Grammarly or similar).
- [x] This PR follows the [Google Developer Documentation Style Guidelines](https://developers.google.com/style) — for example, it doesn’t use _i.e._ or _e.g._, and it avoids _I_ and _we_ (first person).
- [x] This PR uses [semantic line breaks](https://github.com/dart-lang/site-shared/blob/main/doc/writing-for-dart-and-flutter-websites.md#semantic-line-breaks) of 80 characters or fewer.

2023-06-05 15:04 UTC, sfshaza2 requested changes
LGTM, after fixing a couple links. Also, even though you only modified the _comment_ in a Dart code snippet, the build is failing because you need to run the tool/refreshcodeexcerpts command.

2023-06-05 15:04 UTC, sfshaza2 commented on src/platform-integration/ios/platform-views.md
> +[iOS Platform View Backdrop Filter Blur design doc]: flutter.dev/go/ios-platformview-backdrop-filter-blur
```suggestion
[design-doc]: {{site.main-url}}/go/ios-platformview-backdrop-filter-blur
```

2023-06-05 15:04 UTC, sfshaza2 commented on src/platform-integration/ios/platform-views.md
> +See the [iOS Platform View Backdrop Filter Blur design doc] for details.
```suggestion
For more details, check out the [iOS Platform View Backdrop Filter Blur design doc][design-doc].
```

As per GSDG, the condition goes first.

2023-06-08 13:26 UTC, leighajarett commented
@atsansone can you approve this?

2023-06-08 17:42 UTC, cyanglaz commented on src/platform-integration/ios/platform-views.md
> +For example, as shown in `FLNativeView.swift`:
Should this be `FLNativeView.h` for Objective-C?

2023-06-08 20:25 UTC, sfshaza2 approved these changes
lgtm, once @cyanglaz's question is addressed!

2023-06-09 18:43 UTC, atsansone approved these changes

2023-06-12 17:46 UTC, merged