Fixed bottom overflow issue #8728
flutter/website pull request #8855
Opened 2023-06-08 08:37 UTC by AKR-2803

_Description of what this PR is changing or adding, and why:_

This PR is related to image bottom overflow and const keyword warning(#8728). Please review it.

_Issues fixed by this PR (if any):_ 
- #8728

## Presubmit checklist

- [x] This PR doesn’t contain automatically generated corrections (Grammarly or similar).
- [x] This PR follows the [Google Developer Documentation Style Guidelines](https://developers.google.com/style) — for example, it doesn’t use _i.e._ or _e.g._, and it avoids _I_ and _we_ (first person).
- [x] This PR uses [semantic line breaks](https://github.com/dart-lang/site-shared/blob/main/doc/writing-for-dart-and-flutter-websites.md#semantic-line-breaks) of 80 characters or fewer.

2023-06-08 20:31 UTC, sfshaza2 requested changes
Hi, @AKR-2803!  Thanks for this PR!  However, I can't accept it, as you have changed too much of our standard formatting. Not only do we indent all "note" text by 2 spaces, but we also. prefer asterisks for lists.

You did appear to run tool/refresh-code-excerpts, so thanks for that!

If you can undo those changes, I can otherwise accept this PR.

2023-06-08 20:31 UTC, sfshaza2 commented on src/codelabs/implicit-animations.md
> +where to make these changes.
Actually, we always indent note text by 2 spaces.

```suggestion
  You can reference the line numbers in the example code to help track
  where to make these changes.
```

2023-06-08 20:31 UTC, sfshaza2 commented on src/codelabs/implicit-animations.md
> +The `AnimatedOpacity` widget manages everything in between.
Once again, indent note text by 2 spaces.

```suggestion
  Notice that you only need to set the start and end values of `opacity`.
  The `AnimatedOpacity` widget manages everything in between.
```

2023-06-10 08:34 UTC, AKR-2803 commented
Hi @sfshaza2, I just noticed it was a code formatting extension in VS code which caused the formatting issues. However, I have comitted necessary changes. Please review it.

2023-06-14 00:59 UTC, sfshaza2 approved these changes
lgtm!

2023-06-14 01:01 UTC, sfshaza2 commented
@AKR-2803, ack! I see that the build wants you to run tool/refresh-code/excerpts again. Otherwise, this looks great!

2023-06-28 22:57 UTC, atsansone commented
@sfshaza2 : I updated two code-excerpts problems that I found locally. I can't see where the others are. Could you point them out?

2023-08-07 16:54 UTC, sfshaza2 commented
@atsansone, I meant to respond last week. So, I spoke to @parlough about this issue. When you look at the log for the build, it says that 4 examples are a problem, but doesn't identify the exact examples. @parlough, tells me that the build can't really do that. He also stated that fixing these errors manually isn't recommended as they can be quite gnarly. He recommended fixing them using the refresh script. In order to run the refresh script locally, you have to have Docker running and set up. Have you tried that?

2023-08-22 01:02 UTC, atsansone commented
Continuing in #9213 as original editor did not return to this PR.

2023-08-22 01:02 UTC, closed without merging