Add missed semicolons
flutter/website pull request #9475
Opened 2023-10-03 05:59 UTC by DemX86

2023-10-03 20:35 UTC, atsansone approved these changes

2023-10-03 20:41 UTC, atsansone requested changes
This edit needs to be made in the Dart file referenced in the code_excerpt tag. If that file and this excerpt don't match, the build throws a blocking error.

2023-10-04 06:50 UTC, DemX86 commented
@atsansone
The code excerpt for this example was fine already—the problem was with the `replace` regular expression which intents to strip the `return` keyword and the trailing semicolon from the excerpt code.

2023-10-04 15:44 UTC, parlough approved these changes
Thanks!

2023-10-04 17:06 UTC, atsansone approved these changes

2023-10-04 17:06 UTC, merged