Replace primarySwatch with ColorScheme.fromSeed in the examples.
flutter/website pull request #9742
Opened 2023-11-01 18:42 UTC by droidbg

### Description

As a part of Issue: #9713 
this PR updates and replace all instances of `primarySwatch` with `ColorScheme.fromSeed` in the `examples/cookbook` and in remaining code. 

## Presubmit checklist

- [X] This PR doesn’t contain automatically generated corrections (Grammarly or similar).
- [X] This PR follows the [Google Developer Documentation Style Guidelines](https://developers.google.com/style) — for example, it doesn’t use _i.e._ or _e.g._, and it avoids _I_ and _we_ (first person).
- [X] This PR uses [semantic line breaks](https://github.com/dart-lang/site-shared/blob/main/doc/writing-for-dart-and-flutter-websites.md#semantic-line-breaks) of 80 characters or fewer.

2023-11-01 19:43 UTC, atsansone commented
@droidbg : Thanks for this! Did you have a chance to test the resulting changes? There could be some issues with a straight up change. Let me know. Thanks!

2023-11-01 21:18 UTC, atsansone requested changes
Good work so far. You'll need to check the changes within the pages so you can see where the copy refers to the color in the example. This happens in the **Getting Started** > **From another platform?** pages.

I tested a few examples to verify this change didn't break anything. You may want to check a few more.

Update the copy on those pages and you should be good.

2023-11-01 21:18 UTC, atsansone commented on src/get-started/flutter-for/react-native-devs.md
This page (http://docs.flutter.dev/get-started/flutter-for/react-native-devs/) has a good number of other mentions of color that need to be updated.

2023-11-01 21:18 UTC, atsansone commented on src/get-started/flutter-for/uikit-devs.md
This page also has mentions of color that relate to the examples like [this one on theme](http://localhost:4001/get-started/flutter-for/uikit-devs/#using-a-theme). Check this file for other needed changes and update.

2023-11-01 21:18 UTC, atsansone commented on src/get-started/flutter-for/xamarin-forms-devs.md
Same as UIKit, there are [other mentions of color around the examples](http://localhost:4001/get-started/flutter-for/xamarin-forms-devs/#how-do-i-theme-my-app).

2023-11-01 21:18 UTC, atsansone commented on src/get-started/flutter-for/android-devs.md
Need to update [references to colors](http://localhost:4001/get-started/flutter-for/android-devs/#how-do-i-theme-my-app) in example.

2023-11-01 21:45 UTC, domesticmouse commented on src/get-started/flutter-for/android-devs.md
Do you want these changes to be in this PR, or turn this (and other comments) into issues that can be fixed in follow on PRs?

2023-11-01 21:46 UTC, domesticmouse approved these changes
LGTM on the code front

2023-11-02 00:49 UTC, droidbg commented on src/get-started/flutter-for/react-native-devs.md
In this page, I can see all the instances of `primarySwatch` are covered, do we need to change other colors like `primaryColor` also? 

<img width="1708" alt="image" src="https://github.com/flutter/website/assets/41873024/584dea0b-6514-4e5d-9f50-4bf32437ecc4">

2023-11-02 00:57 UTC, droidbg commented on src/get-started/flutter-for/react-native-devs.md
okay I think I got it , you mean mentions like this in text :
<img width="964" alt="image" src="https://github.com/flutter/website/assets/41873024/6e0692b6-8d40-4a10-be59-9589f114a290">

2023-11-02 01:16 UTC, droidbg commented
@atsansone @domesticmouse Thanks for the review, I have done the mention changes.

2023-11-02 22:04 UTC, atsansone approved these changes
@droidbg : Great work! Thanks so much! Approved!

2023-11-02 22:08 UTC, merged