Create adapt-to-large-screens
flutter/website pull request #9946
Opened 2023-12-20 01:11 UTC by mariamhas

_Description of what this PR is changing or adding, and why:_

_Issues fixed by this PR (if any):_

## Presubmit checklist

- [ x] This PR doesn’t contain automatically generated corrections (Grammarly or similar).
- [ x] This PR follows the [Google Developer Documentation Style Guidelines](https://developers.google.com/style) — for example, it doesn’t use _i.e._ or _e.g._, and it avoids _I_ and _we_ (first person).
- [x ] This PR uses [semantic line breaks](https://github.com/dart-lang/site-shared/blob/main/doc/writing-for-dart-and-flutter-websites.md#semantic-line-breaks) of 80 characters or fewer.

2023-12-21 19:45 UTC, sfshaza2 requested changes
@mariamhas, I have some rather large edits I'd like to see for this page. Perhaps we can hash it out in a Google doc? My comments include a fairly significant reorganization. I'm happy to meet via GVC if that helps, though I do have next week off.

2023-12-21 19:45 UTC, sfshaza2 commented on src/ui/layout/responsive/adapt-to-large-screens.md
> +  ratings by device type and notify users when an app lacks large screen support.
Are there benefits to iOS apps, as well?

```suggestion
When your app supports large screens, it also receives the
following benefits:

* Improves your app's metrics to show increased user engagement
  when optimized to fill the screen.
* Increases your app's visibility in the Play Store.
  Recent [Play Store updates][] show ratings by device type and
  indicates when an app lacks large screen support. 
```

2023-12-21 23:05 UTC, mariamhas commented
@sfshaza2 thanks for reviewing shams! I added you to the doc where I had originally written this pr. There is no rush, happy to meet in the new year to discuss changes!

2024-01-29 20:05 UTC, sfshaza2 commented
I'm closing this, because I'm working on updating that section. But I WILL use some of your great content, @mariamhas!

2024-01-29 20:05 UTC, closed without merging